### ISSUE TITLE
Reformat source key

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#109]
Currently, the `key` of a source in `sources.bib` is reformatted upon import into the app from `Author, year` to `Author (year)`. Since the `key` does not serve any other purpose than a somewhat human readable label of the source, it should be already stored as required by the app.

**Comment by kirbykat** [comment]
@xrotwang, quick question about adding/editing sources. Hannah's RAs made some corrections to the EA references (they revisited Murdock's original journal articles to see if some refs had been missed in the summary versions I was working with). 

I will go through their corrections, but am I right that to add a reference for an EA society I would:

1) create a unique reference key for the new source (e.g., Abadie (1924)) and add it to the references column in the "data.csv" file.

2) enter the info for that reference in the sources.csv file, in bibtex format:
e.g., @book{abadie1924,
    author = {Abadie, Maurice},
    title = {Les races du Haut-Tonkin},
    address = {Paris},
    year = {1924},
    url = {https://archive.org/details/McGillLibrary-103431-303},
    key = {Abadie (1924)}
}

And, related, can you point me to the source you followed when converting to bibtex? E.g., did you generate that first part (@book{abadie1924) from author(s) + year, or did you get it from WorldCat or some other library database?

And, should the key in this newly formatted file still work with the old reference look-up files we were using, or have some been corrected?

Thanks...

**Comment by kirbykat** [comment]
@xrotwang Just read your note above about the app reformatting from  from Author, year to Author (year)

**Comment by xrotwang** [comment]
In the references column in data.csv you should add the bibtex key, i.e.
abadie1924, and yes, that's just the ascii-only variant of the unique label.
Am 20.04.2017 21:52 schrieb "kirbykat" <notifications@github.com>:

**Comment by xrotwang** [comment]
Some keys have been corrected, e.g. to merge binford and EA refs.
Am 20.04.2017 21:52 schrieb "kirbykat" <notifications@github.com>:
