### ISSUE TITLE
README.md's in {datasets,phylogenies}

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#113]
As we move to making the `dplace-data` repository more usable for external users, it's more likely that the files can be accessed from e.g. the github interface. 

We should therefore have README.md's in each directory in `datasets` and `phylogenies` to tell people the source of the data and how to cite it. These could be automatically generated from a template using the information in [index.csv](https://github.com/D-PLACE/dplace-data/blob/master/datasets/index.csv) and [source.bib](https://github.com/D-PLACE/dplace-data/blob/master/phylogenies/bowern_and_atkinson2012/source.bib)

**Comment by xrotwang** [comment]
Yes, although I'm not sure how to distribute/mix automatically generated parts and e.g. documentation of the data structure. Maybe put all manually edited stuff in `/README.md`?

**Comment by xrotwang** [comment]
The info in `*/index.csv` is also already used to create https://github.com/D-PLACE/dplace-data/blob/master/SOURCES.md

**Comment by SimonGreenhill** [comment]
Yeah I don't like that either, but I'm just thinking of the use case where someone is poking around github and wants to use e.g. the tree in [kitchen et al](https://github.com/D-PLACE/dplace-data/tree/master/phylogenies/kitchen_et_al2009). 

Maybe it's not a problem -- are people savvy enough to go to the top level to figure out what's the right citation etc? 
 
This idea occurred to me as I was looking at Claire's website trying to find the best source for the bowern and atkinson tree. I thought it might be nice to add a [link to that location](http://www.pamanyungan.net/papers/computational-phylogenetics-and-the-internal-structure-of-pama-nyungan/). 

Maybe we could require one to add a new dataset/phylogeny? (and auto-generate them based on a simple template for now?). 

Actually, this could provide a good place to *document* the datasets and pre-load that information into the dplace webapp?

**Comment by xrotwang** [comment]
@SimonGreenhill you mean require a URL to the source of the actual tree? Maybe the better (more extensible) solution would be a comment in markdown for each dataset/phylogeny which may or may not contain a URL for a source? I think these short descriptions work quite well to give some context for the Concepticon concept lists.

**Comment by xrotwang** [comment]
Oh, and I agree, having a generated README.md per dataset/phylogeny would be good. We could follow the lexibank model, having a comment.md, which is included when generating the README.md - or follow the Concepticon model and have the comment in `index.csv`.

**Comment by SimonGreenhill** [comment]
I realised  we should add acknowledgements/thanks/etc to some of these datasets. Do we want to put these in the README.md or in the index.csv? I slightly prefer README.md as it's closer to the data, and it's easier to edit.

**Comment by SimonGreenhill** [comment]
I realised that this information (only acknowledgements so far) is now in https://github.com/D-PLACE/dplace-data/blob/master/phylogenies/README.md, so we don't need per-dataset READMEs at the moment. Closing this until it becomes necessary.
