### ISSUE TITLE
language family and region missing from EA data

### ISSUE THREAD

**Issue by petyaracz** [D-PLACE/dplace-data#117]
the html d-place interface provides language family and region for each society. it's not available in the data here. is the idea that the user should consult glottolog?

(I am writing code that cites the github repo for the data analysis. I might keep bumping into tiny things like this. Sorry if queries are daft. I don't want to edit the repo.)

**Comment by xrotwang** [comment]
You could retrieve the language data from glottolog in a programmatic way, too (see https://github.com/clld/glottolog). But the relevant parts for D-PLACE are also in https://github.com/D-PLACE/dplace-data/blob/master/csv/glottolog.csv

Mapping from societies to TDWG regions is provided here: https://github.com/D-PLACE/dplace-data/blob/master/geo/societies_tdwg.json

**Comment by petyaracz** [comment]
thank you. 

the language family labels are different for html dplace and the glottolog dataset on the dplace github. the former seem to refer to higher branches. are the html language family labels available somewhere?
they are used very often in mixed-effects models. the entry for Saramaccan is different in the two sets, though I can't seem to figure out how exactly.

**Comment by xrotwang** [comment]
Hm. I don't see a difference between [this record](https://github.com/D-PLACE/dplace-data/blob/master/csv/glottolog.csv#L13447):
```
sara1340,Saramaccan,indo1319,Indo-European,srm
```
and the language family *Indo-European* listed for [Saramaccan online](https://d-place.shh.mpg.de/society/Sc6).

**Comment by petyaracz** [comment]
language family thing was entirely my fault -- the glottolog csv is sorted in such a way that the empty cells come first for lang fam and that confused me. I'll look into what's going on with Saramaccan, as that's probably somehow also me.
