### ISSUE TITLE
Main focal year of eight Binford societies entered as "0"

### ISSUE THREAD

**Issue by Joseph-Watts** [D-PLACE/dplace-data#118]
Hi, 
there are eight cultures in the Binford societies file that have the focal year entered as "0". These societies are:

Worrorra 
Karajarri
Lassik
Mattole-Bear River 
Lake Miwok
Tillamook
Mikea
/Xam

They have years associated with them in other Binford datasets so I was wondering whether this was an error, or if there was a reason they were excluded from DPlace? If they were excluded for a reason then NA might be more appropriate. 
Cheers,
Joseph

**Comment by xrotwang** [comment]
@kirbykat any idea?

**Comment by SimonGreenhill** [comment]
I have checked and fixed this using Amber Johnson's version [of the data](http://ajohnson.sites.truman.edu/data-and-program/) in #119 c46ba4f .
