### ISSUE TITLE
Check of SCCS categories is needed

### ISSUE THREAD

**Issue by Bibiko** [D-PLACE/dplace-data#130]
@kirbykat please check category names: `labor` vs. `labour`, `life cycle` vs. `lifecycle`

**Comment by Bibiko** [comment]
I can fix this once we've agreed on a spelling variant for each of both issues

**Comment by Bibiko** [comment]
@kirbykat @xrotwang [stop - main question: where does live the original data now? GitHub or kirbykat's csv files?? ]

**Comment by kirbykat** [comment]
yes, good question, I was wondering where best to make changes.
let's go with 'labour' and 'life cycle'...

**Comment by Bibiko** [comment]
@xrotwang @kirbykat ok - for now I do these changes in the GitHub repo for SCCS variables.csv but it would be good that you do it in your csv file as well since the missing definitions will come.
