### ISSUE TITLE
Replace reference fields in datafiles with citekeys

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#134]
I realised that we have the reference in [index.csv](https://github.com/D-PLACE/dplace-data/blob/master/datasets/index.csv). Do we need it there? it's a pain to curate, and we should just be able to list the bibtex cite key from [sources.bib](https://github.com/D-PLACE/dplace-data/blob/master/datasets/sources.bib)

**Comment by xrotwang** [comment]
I agree. In the worst case, e.g. if we wanted a particular linearization of the bibliographic data as citation, we could stick this as additional field into the bibtex file as well. And we should do this for both, datasets and phylogenies.

**Comment by SimonGreenhill** [comment]
Just realised that this also goes for [variables.csv](https://github.com/D-PLACE/dplace-data/blob/master/datasets/SCCS/variables.csv) which includes sources (much easier and smaller to have a citekey there), and I'm sure there are other files with references in them too.

**Comment by xrotwang** [comment]
For the SCCS variables we actually have both, bibtex file and mapping between text citation and bibtex key. Not for the other datasets, though.

**Comment by kirbykat** [comment]
@SimonGreenhill In the case of SCCS, the references in APA format are  
just placeholders for better variable definitions (so, when you select  
a variable like "Fish", it says "Further information: Murdock and  
Morrow, 1970, etc etc". The Murdock and Morrow article defines the  
variables and codes.
