### ISSUE TITLE
Consolidate bibtex files

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#135]
We currently have bibtex files all over the place:

```
./datasets/sources.bib
./phylogenies/bouckaert_et_al2012/source.bib
./phylogenies/bowern_and_atkinson2012/source.bib
./phylogenies/chacon_and_list2015/source.bib
./phylogenies/chang_et_al2015/source.bib
./phylogenies/dunn_et_al2011_utoaztecan/source.bib
./phylogenies/gray_et_al2009/source.bib
./phylogenies/grollemund_et_al2015/source.bib
./phylogenies/honkola_et_al2013/source.bib
./phylogenies/kitchen_et_al2009/source.bib
./phylogenies/lee_and_hasegawa2011/source.bib
./phylogenies/michael_et_al2015/source.bib
./phylogenies/sicoli_and_holton2014/source.bib
```

i.e. datasets/ has a combined sources.bib, while each phylogeny has a single source.bib. 

Should we consolidate these into a single sources.bib, perhaps in its own top level file (./sources.bib)? or keep them as dataset specific resources?

**Comment by xrotwang** [comment]
I'd vote for "consolidate on top-level". This way, it would also be simpler to reference these sources in descriptive text on the website: Just lookup the bibtex key in the one bib file and have a template function which turns this into a full reference link.

**Comment by SimonGreenhill** [comment]
Yes, and it's DRYer.

**Comment by SimonGreenhill** [comment]
Can I just merge these now, or does there need to be some change to `pydplace` too?

**Comment by SimonGreenhill** [comment]
Done in https://github.com/D-PLACE/dplace-data/pull/272

**Comment by xrotwang** [comment]
I don't think `pydplace` looks at these atm:
```
$ grep -r sources.bib src/
src/pydplace/api.py:        return BibFile(self.path('datasets', 'sources.bib'))
```

**Comment by xrotwang** [comment]
Ah, ok. If you merge `datasets/sources.bib`, too, it'll need to change.

**Comment by SimonGreenhill** [comment]
Yeah, just realised that's why the tests were failing :) What do you think -- a top level sources.bib (so change pydplace) or a bib in `datasets/` and `phylogenies/`?

**Comment by xrotwang** [comment]
top-level, I think. It's still fairly small.

**Comment by SimonGreenhill** [comment]
Yeah, that makes sense -- shall I make a PR for pydplace?

**Comment by SimonGreenhill** [comment]
Oops, sorry -- I think I pushed to master on pydplace last night. Should have gone to bed earlier :/
