### ISSUE TITLE
Ensure csv downloads include all available "contextual" information

### ISSUE THREAD

**Issue by kirbykat** [D-PLACE/dplace-data#142]
Currently "contextual" information is provided at the level of VARIABLES, CODES, and DATA

E.g., 
DATA: Subcase, Year, Comments, EthnoRefs, SourceCodedData, AdminComments
CODES: UserNotes, adminComments, Source
VARIABLES: UserNotes, adminComments, Source 

Currently, if I download coded data for three variables, do I get the variable definitions, user notes, admin comments etc. for those variables?  What about notes on the code definitions? Finally, what about comments on the specific data value?

This info is all included in the original CSV files - how do we make sure it is not lost?

**Comment by xrotwang** [comment]
I'd say the way to go is to advertise the data repository (and it's python API) as **the** way to access the data for quantitative work - over the csv download on the website. De-emphasizing web-app functionality may also help with long-term maintenance.

**Comment by kirbykat** [comment]
Ok, that does sounds like a good approach. A related question, though - it seems that some columns are currently pruned off the CSV files I have prepared, before being saved to the repository. Though it's also possible I am mis-understanding where things are stored...

For example, compare this file 
https://github.com/D-PLACE/dplace-data/blob/master/datasets/SCCS/variables.csv

with this file:
https://www.dropbox.com/s/ejisurc169cojyj/SCCS_Full_VariableList_13Sept2017_win1252.csv?dl=0

AdminNotes are missing...(and granted, I could clean those up, but at least they give the original STDS files for anyone delving into the World Cultures files).

**Comment by xrotwang** [comment]
@kirbykat Yes, I only incorporated columns into the respective csv files which we also have in the other datasets - but adding more wouldn't be a problem. We just have to get away from defining a new data schema with each iteration of work on data.

**Comment by xrotwang** [comment]
We will advertise the data repository and it's python API to access the data programmatically.
