### ISSUE TITLE
Recover the textual information for SCCS v1716-v1780

### ISSUE THREAD

**Issue by kirbykat** [D-PLACE/dplace-data#145]
@bibiko @xrotwang @SimonGreenhill  - are you able to extract data from a dBase database? See below.

"A disk included with this volume holds zipped files for the CONAN data base and a copy of a program needed to unzip the files. The CONAN date base requires dBASE IV (or later) to run and the files must be unzipped to a hard drive.  The numeric codes in ST81.DAT and ST82.DAT duplicate to codes in CONAN, **but you cannot recover the textual information in coding decisions for specific cases without running the dBASE program.**"

"The CONAN materials on the disk should all be copied to directory on
your hard disk. If you have a directory dedicated to dBASE files you might
want to copy it to that directory.  Unzip the compressed files by issuing
the commands: "pkunzip conan" and "pkunzip concodes".  To use the CONAN
materials start dBASE and open the CONAN database."

Here's a link to the zipped 'conan' and 'concodes' files: 
https://www.dropbox.com/s/654xp89abk8tpm0/CONAN.ZIP?dl=0
https://www.dropbox.com/s/qy624qlmwjqgvr6/CONCODES.ZIP?dl=0

Text file describing the files (conan includes 67 codes for a 101 society subsample of the SCCS):
https://www.dropbox.com/s/7o7v4scv7h7fjj6/Conan.txt?dl=0

And the MAPTAB files (from which I've already extracted the variables and codes - they do not contain textual info):
https://www.dropbox.com/s/kxtgm6wbechcbns/STDS81_82_CONAN_MAPTAB.zip?dl=0

**Comment by Bibiko** [comment]
DBF files can be read by using LibreOffice/OpenOffice quite easily if one knows the text encoding (but this shouldn't be the problem here)

**Comment by xrotwang** [comment]
Yes, extracting the data is not too much of a problem. What exactly do you want to do with it, though? Is this going to be a separate dataset, or should it replace/supersede/correct the SCCS data for the corresponding societies and variables?

**Comment by xrotwang** [comment]
@kirbykat This is what `csvstat` tells me for the DBF file converted to csv:
```
$ csvstat conan.csv 
  1. VAR_NO
	<type 'unicode'>
	Nulls: False
	Unique values: 71
	5 most frequent values:
		56:	101
		54:	101
		42:	101
		48:	101
		43:	101
	Max length: 13
  2. VAR_VALUE
	<type 'unicode'>
	Nulls: True
	Unique values: 165
	5 most frequent values:
		99:	1218
		1:	972
		3:	801
		2:	725
		88:	583
	Max length: 7
  3. MODFD_VAL
	<type 'int'>
	Nulls: False
	Min: 0
	Max: 99999
	Sum: 777253
	Mean: 109.921227549
	Median: 10
	Standard Deviation: 1282.68835766
	Unique values: 164
	5 most frequent values:
		99:	1218
		1:	972
		3:	801
		2:	725
		88:	583
  4. SOURCE_S
	<type 'unicode'>
	Nulls: True
	Unique values: 952
	5 most frequent values:
		A:Osgood 1951:	70
		A:Holmberg 1969:	70
		A: Elmendorf, W. 1960:	69
		A: Maybury-Lewis, D. 1967:	68
		A:Goldman 1963; B:Goldman 1948:	68
	Max length: 60
  5. TEXT_COM
	<type 'unicode'>
	Nulls: True
	Unique values: 5366
	5 most frequent values:
		[Variable 30=10 (No political office)]
 Orokaiv:	8
		[var 30 = 10; there is no political authority beyond the family- 
unit]
chter un:	7
		A 47: Apart from this generalized and mainly symbolic 
identification of members with the camp community, the group is 
rarely mobilized as a corporate unit in conflict situations with 
other groups. The prevailing fear and suspicion keeps groups at a 
reasonable distance from each other, and violent conflicts occur 
only rarely. Fights with sticks and stones may occasionally 
develop over pastures between shepherds from different camps, and 
when these take place sufficiently close to camp the whole group 
may join in the fray. I never ovserved such a case in the field; 
the Darbar camp had been involved in one the previous year.
d as a c:	5
		D 291: But now, at any rate, they are as peaceful as it is 
possible to be.
re said:	4
		D 291: But now, at any rate, they are as peaceful as it is 
possible to be.
hed his:	4
	Max length: 5045
  6. CASE_NAME
	<type 'unicode'>
	Nulls: True
	Unique values: 104
	5 most frequent values:
		Thonga:	70
		Yurok:	70
		Kung Bushmen:	70
		Yanomamo:	70
		Koreans:	70
	Max length: 15
  7. SCCS_NO
	<type 'int'>
	Nulls: True
	Min: 2
	Max: 186
	Sum: 654968
	Mean: 92.6535577875
	Median: 92
	Standard Deviation: 53.3568721142
	Unique values: 101
	5 most frequent values:
		133:	70
		132:	70
		130:	70
		136:	70
		135:	70
  8. CODER_NAME
	<type 'unicode'>
	Nulls: True
	Unique values: 10
	5 most frequent values:
		ba:	1260
		UR:	1259
		ra:	1229
		sa:	1190
		kl:	1050
	Max length: 4

Row count: 7071
```

**Comment by kirbykat** [comment]
@xrotwang It won't replace existing variables - codes (they should be the same), but I'd like to extract the Comments for each society-variable-code combination. 

These look like comments:

A47: Apart from this generalized and mainly symbolic 
identification of members with the camp community, the group is 
rarely mobilized as a corporate unit in conflict situations with 
other groups. The prevailing fear and suspicion keeps groups at a 
reasonable distance from each other, and violent conflicts occur 
only rarely. Fights with sticks and stones may occasionally 
develop over pastures between shepherds from different camps, and 
when these take place sufficiently close to camp the whole group 
may join in the fray. I never ovserved such a case in the field; 
the Darbar camp had been involved in one the previous year.

D 291: But now, at any rate, they are as peaceful as it is �
possible to be.

**Comment by xrotwang** [comment]
Should they be added as `comment` in [SCCS/data.csv](https://github.com/D-PLACE/dplace-data/blob/master/datasets/SCCS/data.csv)? This could presumably be done programmatically.

**Comment by kirbykat** [comment]
Yes, that would be wonderful.

**Comment by kirbykat** [comment]
It would also be ideal to figure out the relationship between SOURCE_S and SOURCE_NO, and to include this info in "EthnoReferences" (presumably these are the first authors and page numbers from which cultural data are taken)

**Comment by xrotwang** [comment]
Ok. That seems doable - it should be possible to
- extract sources (and match them to sources we already have)
- extract page numbers from the comment fields (and replace the single-letter source keys in the comments with bibtex keys)
- add these comments to data.csv

**Comment by kirbykat** [comment]
Do you think comments are the best place for page numbers? I know we are trying to minimize changes to the schema, but perhaps we should pair each "source" and "ethnoReferences" field with a "page number" field. I think this would save having to extract this information from a comments field in the future. (And here, the comments field will sometimes contain quite a long comment from the TEXT_COM field.)

**Comment by xrotwang** [comment]
I think page numbers should be part of a reference, i.e. belong into the `Source` field. We are basically re-engineering the CLDF spec here, see https://github.com/glottobank/cldf/blob/master/core.md#data-files
In any case we can leverage some of the machinery I built for it, e.g. a csv reader/writer which can deal with [secondary separators](http://w3c.github.io/csvw/metadata/#cell-separator) within cells of csv files. This makes markup like the one we'll use for the `Source` field less error-prone.

**Comment by kirbykat** [comment]
Great, so something like this:  meier2015[3-12], where meier2015 is the bibtex tag. Sounds good.

**Comment by xrotwang** [comment]
exactly

**Comment by xrotwang** [comment]
@kirbykat Is there a reason for mapping the CONAN code numbers to other numbers, e.g. 
> SCCS1719,4,seldom (occurrence uncommon) (original code 31),seldom

It doesn't seem that codes across variables have any shared semantics, so I think it would be less error-prone to just keep the CONAN numbers. In fact, in the example, the CONAN numbers may even add the information that cases 31 and 32 are special cases of code 30?

**Comment by kirbykat** [comment]
@xrotwang I would lean towards going with the original CONAN code numbers. In my experience, information has often been left out in 're-coding' initiatives, so your hunch that 31 and 32 are special cases of 30 could very well be correct (I still have not delved into the original CONAN data myself...)

**Comment by xrotwang** [comment]
@kirbykat I'm back to extracting the SCCS data from the CONAN files. I have 6 cases where the coded value isn't listed in the codebook. 4 of these specify a value of `10` for variable `27` (in CONAN terms), This variable is described in the codebook as
```
27 - Extent of burden caused by tribute payments or taxation

	99	=	missing data
	88	=	no tribute or taxation
	20	=	sporadic taxation or request for tribute
	21	=	the exactions are reported not to be burdensome
	22	=	the exactions are reported to be burdensome
	30	=	regular taxation or request for tribute
	31	=	the exactions are reported not to be burdensome
	32	=	the exactions are reported to be burdensome
```
The current description of the corresponding variable in the SCCS dataset does not seem to match this description:
```
SCCS1737,0,no tribute or taxation (original code 88),no tribute or taxation
SCCS1737,1,sporadic taxation or request for tribute (original code 10),sporadic taxation or request for tribute
SCCS1737,2,the exactions are reported not to be burdensome (original code 20),the exactions are reported not to be burdensome
SCCS1737,3,the exactions are reported to be burdensome (original code 21),the exactions are reported to be burdensome
SCCS1737,4,regular taxation or request for tribute (original code 30),regular taxation or request of tribute
SCCS1737,5,the exactions are reported not to be burdensome (original code 31),the exactions are reported not to be burdensome_duplicated_5
SCCS1737,6,the exactions are reported to be burdensome (original code 32),the exactions are reported to be burdensome_duplicated_6
```
Note that the description given here for `original code 10` is the one for `20` in the codebook.

This also seems to be a case, where the numbers in the codebook clearly are meant to convey a relation between the codes: 
- `21` means *non-burdensome sporadic taxation*
- `31` means *non-burdensome regular taxation*

Technically such variables are **not** categorical, because the codes do not form a [partition](https://en.wikipedia.org/wiki/Partition_of_a_set) of the design space. So either we should turn them into proper categorical variables (i.e. have codes *sporadic (no info on burden)*, *sporadic, burdensome*, *sporadic, non-burdensome*, ...), or not label them as such.

**Comment by xrotwang** [comment]
@kirbykat here are the `TEXT_COM` fields of the 4 offending codings (which may provide an idea what code `10` should be):

> A 74: Clans retained a hierarchical composition, but the ranking of lineage groups within a clan was marked by the titles given to the leaders of each, the concomitant was tribute in cattle.

> [Although no tribute seems to have been paid to foreign authorities, people had to pay taxes to their own king:]
>
> C 97: The simple peasant looked at the once magnificent barays and other water reservoirs which his forefathers had died in building, heard in silence the promises of the king's tax collectors that they would be made good, then quietly and secretly folded his tent and stole away.

> C 218: They [the Ainu] were compelled to pay taxes.

> A 5: It is reported that in the eighteenth century the Chinese appointed headmen or chiefs from among the Nivkh to act as middlemen between the Chinese administration and the people. Apparently, these agents carried no authority or weight whatsoever once the Chinese military detachment and tax collector were out of sight.

**Comment by kirbykat** [comment]
@xrotwang - I need to take a look at the detailed descriptions, and will try to do this later today. In other datasets, double-digit codes were often used to present two pieces of info "under" the same variable I'd (first digit of code signifies one thing, second something else). Later versions of datasets often split these into two separate variables. Are there some variables that appear in our SCCS version of the CONAN dataset but not in the original Dbf files? If so, the double digit original may have been split in the version currently on the DPLACE site. In some cases I think this splitting is preferable, but i have so far assessed these on a case-by-case basis.

**Comment by xrotwang** [comment]
AFAICT the 65 variables from CONAN appear in order and with the same variable description (although changed code descriptions) in our version of SCCS.

**Comment by xrotwang** [comment]
@kirbykat as a first step - I think - we should re-instate the original CONAN code numbers in our SCCS dataset.

**Comment by kirbykat** [comment]
@xrotwang that sounds good to me. However, are you ok with replacing the original codes for missing data with "NA"s, to keep things consistent across D-PLACE? I noticed the missing data code was 99 in the example you gave.

**Comment by xrotwang** [comment]
Yes, 99 for missing data is consistent across variables in CONAN and can be consistently replaced with NA.

**Comment by xrotwang** [comment]
@kirbykat Another question: You said not aggregating data is one of the selling points of D-PLACE. So considering we also allow continuous variables, shouldn't CONAN's variable 46, *Size of local community*, be kept with the original, non-binned values, rather than with the codes
```
SCCS1756,1,between 10 and 50,between 10 and 50
SCCS1756,2,between 51 and 100,between 51 and 100
SCCS1756,3,between 101 and 150,between 101 and 150
SCCS1756,4,between 151 and 200,between 151 and 200
SCCS1756,5,between 201 and 250,between 201 and 250
SCCS1756,6,between 251 and 300,between 251 and 300
SCCS1756,7,between 301 and 500,between 301and 500
SCCS1756,8,between 501 and 1000,between 501 and 1000
SCCS1756,9,greater than 1001,greater than 1001
```

**Comment by kirbykat** [comment]
@xrotwang Yes! Definitely. And cool that unbinned data are available!
