### ISSUE TITLE
Revised longitude values for WNAI societies in "WNAI" > "societies.csv" place societies in eastern hemisphere

### ISSUE THREAD

**Issue by kirbykat** [D-PLACE/dplace-data#149]
@bibiko, @xrotwang can you tell if this error entered via my files or in the creation of the society.csv file? 

Note that the societies appear in the right place on maps (in western hemisphere).

**Comment by xrotwang** [comment]
For WNAI, `origLong` didn't come in any of the new files you sent, but instead was taken from https://github.com/D-PLACE/dplace-data/blob/master/legacy/LatLong_data.csv
Would have to investigate when and how that file entered the repository. Should I?

I understand that the revised longitudes are correct, right?

**Comment by kirbykat** [comment]
Hi @xrotwang, no, the revised longitudes are not correct - they should all have a minus sign in front of them (*-1), placing them in the western hemisphere. Otherwise they seem to be correct.

**Comment by xrotwang** [comment]
@kirbykat But that's the case: https://github.com/D-PLACE/dplace-data/blob/master/datasets/WNAI/societies.csv
Or which file are you looking at?

**Comment by kirbykat** [comment]
@xrotwang,  ah, sorry, this must been a 2 am-brain related issue. the revised lat/longs are indeed correct.
