### ISSUE TITLE
Fix citation for environmental data

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#151]
> My team and I have been hard at work locating new environmental data to fill in some important gaps in the current version of d-place and to correct what we perceive as limitations of the CRU TS v.3.3. data set. I am happy to announce today that we not only managed to do that, but were also able to get ahold of what we think are much better quality data sets than the ones we had (sources cited below for those that care about the details). Notably, the new variables provide FULL coverage (yes… that includes ALL societies for the info-pacific, which means no more limits on the environmental questions we ask!). Any way, attached are the data and source details. Enjoy!

A)  I’m not sure I know who to contact to update the data on D-PLACE (Simon… is that you or is it still Stephanie? Would you guys mind updating the web page with the new data? ALSO… could someone please update my lab’s web page in D-PLACE’s “team” url? It should be “https://pages.wustl.edu/botero", rather than "http://cabotero.weebly.com/“. Thanks!

B) I believe older variables with the same names as the ones provided here should no longer be distributed to avoid confusion (maybe they could be archived under something like “heritage data”?). The newer data is REALLY much better and we should discourage the use of the older one...

C) NEW DATA AND DATA SOURCES

1) Climate data

Annual mean, annual variance, predictability, constancy and contingency for both precipitation and temperature are now based on the “Baseline Historical (1900-1949), CCSM ecoClimate model”. The source citation is:

Lima-Ribeiro,M. et al. 2015. ecoClimate: a database of climate data from multiple models for past, present, and future for Macroecologists and Biogeographers
Biodiversity Informatics 10, 1-21. PDF

Please note that the definitions for these variables remain identical as what we currently have in D-PLACE but that the basic units for precipitation data are now grams per square meter per month. Big shout out to the folks at ecoClimate.org who kindly shared with us the raw data from their models (something that is not typically distributed to end users), allowing us to compute predictability, constancy and contingency just the way we wanted. 

2) Physical landscape

The current version of D-PLACE includes elevation and slope data from the GTOPO30 dataset (in fact, our current slope data were computed by Rick Step and he never shared with us the exact methods he used, so I am happy to switch to something I can completely vouch for). We have taken advantage of a newer and more accurate data source for elevation: the Global Multi-resolution Terrain Elevation Data 2010 (Link here: GMTED2010), which has replaced the GTOPO30 data over the years. Please note that elevation data from GMTED2010 comes at a whopping 30 ArcSec resolution (!!!) which I use to compute initial —highly local— estimates that are then down sampled to a 0.5 by 0.5 degree resolution in order to maintain consistency with all other D-PLACE variables.

Citation: Global Multi-resolution Terrain Elevation Data courtesy of the U.S. Geological Survey (Downloaded 14 Jul 2014 from http://topotools.cr.usgs.gov/gmted_viewer/)

**Comment by kirbykat** [comment]
Update on precipitation units from Carlos 06/10/2017:

Sorry. It was simply a Freudian typo. I meant ml rather than mm. Our unit is ml/m2/month... mm (which is what one typically reports) indicates the is the amount of rain accumulated in a vessel. Whether you have a wide bucket or a narrow cylinder, you expect the same height to accumulate as long as rain falls evenly across the surface. However, the ecoclimate guys use precipitation flux instead and when you do that, you need to take into account the amount of surface that you are measuring. 2000mm is 200cm (the height of the volume of water being measured) and 1 meter is 100 centimeters (the width and length of the volume being measured) that means that 2000mm of rainfall annually corresponds to:
200cm*100cm*100cm = 2,000,000cubic centimeters of water falling across the meter2 per year. One cubic cm is one ml of water so our measurement of 156628ml/m2/month * 12 months =~ 1900000ml/m2/year. In other words, our estimate for the Guna is basically exactly what is expected for eastern panama. All the best,


Carlos

**Comment by kirbykat** [comment]
SO, summary:

New precipitation units: ml/m2/month
New slope units: degrees

**Comment by stefelisabeth** [comment]
Hi all, sorry only just saw this. Is this the new environmental data from a while ago that we have yet to update on D-PLACE? I believe the last conversation we had about this involved reformatting the data to fit with our current load scripts. I guess that never happened - I'll do it this week/weekend unless it has been done and I'm looking at an older email.

**Comment by xrotwang** [comment]
@stefelisabeth I'll take care of this. Yes, it's the data from a while ago and unfortunately it made its way online.

**Comment by kirbykat** [comment]
This looks like it was fixed last year, but that we somehow then reverted (perhaps a later commit pushed through a non-updated variable definition list, i.e., the ones flagged by @xrotwang: https://github.com/D-PLACE/dplace-data/commit/26c8b8e67f06cde2601bbca759bb8bd825213f9e#diff-77b33c2b54755ecbd98eb853e88ce1ca)

**Comment by xrotwang** [comment]
I think the fixed data just didn't make it to the website.

**Comment by xrotwang** [comment]
"New" D-PLACE has it right: http://dplace.clld.org/parameters/MonthlyMeanPrecipitation

**Comment by kirbykat** [comment]
Well, that’s good. But, aren’t both “Old D-PLACE” and “New D_PLACE” pulling from the same data repository? So, does this mean that we could simply ‘push’ all changes made to repository files since the last update of “Old D-PLACE”, and fix these problems?

Thanks again

**Comment by xrotwang** [comment]
Dunno. I never pushed anything to the production server. Ping @Bibiko

kirbykat <notifications@github.com> schrieb am Di., 12. Juni 2018, 17:03:

**Comment by Bibiko** [comment]
I'll check it if I'm back in Germany this Sunday.

**Comment by xrotwang** [comment]
@Bibiko did you get a chance to check when and what data last got uploaded to the production site?

**Comment by xrotwang** [comment]
@kirbykat @Bibiko Presumably, the data online now is [release 1.1](https://github.com/D-PLACE/dplace-data/releases/tag/v1.1) which has [the wrong variable description](https://github.com/D-PLACE/dplace-data/blob/v1.1/datasets/CRUTS/variables.csv#L4). So I guess what we should do, is 
- either create a bugfix release 1.1.1, just fixing this particular problem
- or create release 1.2 from the current status of the master branch in the data repos

and push the release to production.

**Comment by xrotwang** [comment]
Will be superseded by a D-PLACE 2 release.
