### ISSUE TITLE
Binford societies.csv file - missing or stray quote after update?

### ISSUE THREAD

**Issue by kirbykat** [D-PLACE/dplace-data#153]
After my latest edit, I keep getting this message. Not sure how to fix it, or if needs fixing:

"We can make this file beautiful and searchable if this error is corrected: Missing or stray quote in line 318"

**Comment by xrotwang** [comment]
The double quote `"` is used to mark cells in CSV which contain the delimiter `,`. To make this work, double quotes in these cells must be escaped, typically either using `\"` or `""`. To avoid this ambiguity, I switched the contained double quotes to single quotes.
