### ISSUE TITLE
better descriptions of datasets

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#154]
Datasets should have a description including the text blob which is used on the sources-page of the web app, but also a bit of info about how the data is coded. E.g. for the Binford data we just came across the fact that there are rows in `data.csv` which **only** differ in `comment` and `references`:
```
B1,,1970,B011,30,"Note, first of three estimates provided by Binford (30, 26, 30) for this society","harrison1949:135, 139; urquhart1951:515, 505",Binford_2001_Tables_5.01_and_8.01,"Note, three estimates provided by Binford (30, 26, 30)"
...
B1,,1970,B011,30,"Note, third of three estimates provided by Binford (30, 26, 30) for this society",sellato1994:143-44,Binford_2001_Tables_5.01_and_8.01,"Note, three estimates provided by Binford (30, 26, 30)"
```

This is surely something that can trip up analyses, thus should be mentioned somewhere.

**Comment by kirbykat** [comment]
@xrotwang, we should be able to extract all of this info from the paper we published. The case you describe for Binford is something we pitch as a "selling point" for DPLACE (we present de-aggregated data, so users can get a feel for the variance. In this instance, two separate observations provide a value of 30, which might give the user confidence that this is a representative value for the society). But yes, users who have not read the paper would no doubt be mystified, so perhaps I can work on extracting the relevant details from Kirby et al. 2016.

**Comment by xrotwang** [comment]
Yeah, after writing this comment, it occurred to me that the paper would be the place to describe this. But I still think it would be good to have this info here as well. In particular things that may have bearing on the database schema (like unique constraints) should be mentioned.

**Comment by SimonGreenhill** [comment]
This could probably go in the metadata.json as text blob? or a DESCRIPTION.md file?

**Comment by xrotwang** [comment]
With the data now available as (individual) CLDF datasets, exploratory analysis of the data should be much easier.
