### ISSUE TITLE
Nocodes for ISO 639-3 in D-place

### ISSUE THREAD

**Issue by HedvigS** [D-PLACE/dplace-data#156]
There's 11 languages in D-place that do not have an ISO 639-3 code but where Glottolog has a stand-in "nocode" ISO-code. Sometimes when comparing data, these "nocodes" could be useful. I just noticed this and thought I'd tell you guys :)

calu1239 | NOCODE_Calusa
chon1248 | NOCODE_Chono
guai1237 | NOCODE_Guaicurian
ipai1240 | NOCODE_Ipai
karr1236 | NOCODE_Karruwali
lenc1242 | NOCODE_Lenca-Honduras
port1278 | NOCODE_Port-Sorell
sout1439 | NOCODE_South-Eastern-Tasmanian-Hinterland
tong1329 | NOCODE_Tongva
tule1245 | NOCODE_Tule-Kaweah
yaga1256 | NOCODE_Yagara

**Comment by xrotwang** [comment]
You are not suggesting a proliferation of `NOCODE_`s, are you? If people want them, they could dig them up in the same way you did - by joining Glottolog data on `Glottocode`, no?

**Comment by HedvigS** [comment]
I was just noticing this in the D-place data and thought I'd make that known to the people managing D-place data. Like you say, I can deal with it.
