### ISSUE TITLE
"x" column in WNAI/codes.csv

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#175]
The [code description of the WNAI dataset](https://github.com/D-PLACE/dplace-data/blob/master/datasets/WNAI/codes.csv) has a somewhat mystrious column `x`, with the following statistics:
```
  6. "x"

	Type of data:          Text
	Contains null values:  True (excluded from calculations)
	Unique values:         4
	Longest value:         12 characters
	Most common values:    None (2369x)
	                       FINE (8x)
	                       DISAGREEMENT (6x)
	                       Fine (2x)
```

What does this mean? And do we have to keep it?

**Comment by SimonGreenhill** [comment]
I think these can be deleted safely, right @kirbykat ?

**Comment by kirbykat** [comment]
@xrotwang, @SimonGreenhill - yes, they can be deleted. thanks!
