### ISSUE TITLE
Column for language-level ID in SCCS societies.csv when dialect

### ISSUE THREAD

**Issue by HedvigS** [D-PLACE/dplace-data#180]
When the languoid a society has been mapped to in D-place is a dialect, it would be helpful to have a column for the language level ID. Like this:

https://github.com/glottobank/Grambank/blob/master/exploratory%20analysis/descriptive%20stats/GB_descriptive_stats/Language%20samples/SCCS_new.tsv

Yes, it's perfectly possible to retrieve that yourself but for conveinence this would be handy when we're doing cross-database comparisons.

**Comment by xrotwang** [comment]
`glottolog.csv` in D-PLACE/dplace-data is recreated from the latest released version of clld/glottolog and used as the baseline for all glottocode assignments in D-PLACE.
