### ISSUE TITLE
Songhai society to language mapping

### ISSUE THREAD

**Issue by HedvigS** [D-PLACE/dplace-data#181]
It may also be necessary to just double check Songhai SCCS24, xd480. Some of the ethnographics might be describing other varieties that are not Zarma-Kaado.

Harald wrote:
_RE Songhay, quite possibly Zarma is the best match but looking at the source titles (I don't have the fulltexts handy) I think the SCCS sources listed may also have datapoints from other Songhays in Mali. Might be good with an actual check of the ethnographic sources._

Kate wrote this in the current document:

_Note 8Feb2018: Changed after HH questioned whether specifically Hombori; SCCS notes specify that focus is ""The central Songhai at the bend of the Niger"" [in southwesternmost Niger, i.e. Niamey area]. Appropriate match is therefore Zarma-Kaado._

**Comment by kirbykat** [comment]
This is an ambiguous case., as I believe many of the main sources of the SCCS discuss the Songhai 'people' as a broad group with many subgroups. However, after more searching I do believe a better match would be:
koyr1242 - Koyraboro Senni Songhai (alternative name: Gao Songhai)
or possibly
koyr1240 - Koyra Chiini Songhay (alternative name: Songhai of Timbuctu)

Why:
-SCCS pinpointing sheet states the focus is on the "Bamba, or central division" Songhai at the "bend in the Niger" - I took this to be the area around Niamey on my last read, but in fact it should be in Mali, possibly centered on the town of Bamba (17°02′N 1°24′W)
-Wikipedia describes Bamba as "a small town and rural commune in the Bourem Cercle of the Gao Region of Mali. The town is located on the left (north) bank of the Niger River, 190 km east of Timbuktu and 230 km northwest of the town of Gao. The commune of Bamba includes 19 villages and 7 nomadic population groups. The population are *primarily Songhais* but also Tuaregs and Bozos."
-Bamba falls between the primary field sites of the two anthropologists whose field work dates were used to select a focal year of 1940 for the Songhai case in the SCCS: Timbuktu (H. Miner) and Ayorou (J. Rouch)

Jean Rouch's work focused on the Songhai in general - for example his 1960 book discusses the influence of Songhai subgroups (Sorko, Gow) and neighbouring  non-Songhai groups on Songhai religion. 

Wikipedia describes one of Rouch's primary field sites as the town of Ayorou, on the Niger-Mali border, 208 km northwest of the capital Niamey
Regarding the possible match to zarm1239 -- both popular (wikipedia) and formal (academic book reviews) descriptions of Rouch's work often mention his interest/work on the "Zarma and Songhai"

Rouch, J. 1954. Les Songhay. Paris.
Rouch, J. 1960. La Religion et la Magie Songhay. Paris.

Miner's book focuses on three ethnic groups in the town of Timbuktu, one of which is the Songhai. ["The Primitive City of Timbuctoo is a report of the life and customs of three major ethnic groups living in this ancient city, as seen by Mr. Miner during a seven months' residence there. The three groups studied were the Arabs, the Songhoi, and the Taurey. The author shows that each of these groups casts its influence upon the religion, customs, mores, education, and life in general of all its inhabitants, e.g., Arabs on Songhoi and vice versa. [...] The author gives a clear picture of the geographical location of Timbuctoo and the surrounding countries and a very vivid and picturesque description of the marriage and divorce customs of each of the groups. He likewise furnishes interesting details and other information of birth customs, birth rates, death, and burial practices of each of the great groups, reporting numerous of their beliefs in life after death, the types of spirits believed in, and methods of controlling or appeasing the evil spirits."

Here is a bit more detail on how the architects of the SCCS viewed Songhai divisions: (from the society's SCCS pinpointing sheet (Murdock and White, 1969)):

The Songhai are divided into:
(1) the Bamba (Central Songhai, centered on the bend of the Niger River in Mali -- this group is the focus for the SCCS "as they are the best known to history"), 
(2) the Kadobi (eastern Songhai, around Tillabery), and 
(3) Galibi Arb (western Songhai, around Goundam and Niafunke).

**Comment by HedvigS** [comment]
Thank you so much @kirbykat ! I know it takes time to go through and investigate this.
Lucky for is in GB, we already have koyr1242 and koyr1240 :D!

**Comment by kirbykat** [comment]
Done as part of #183
