### ISSUE TITLE
Toradja society to language mapping

### ISSUE THREAD

**Issue by HedvigS** [D-PLACE/dplace-data#182]
Harald wrote:
_The Toradja described by Adriani-Downs is Pamona [pmf], not Sa'dan [sda]. Drabbe (1940) is about a quite different island/language (Fordata [frd]) but maybe it has remarks on Pamona [pmf] which was a main mission post._

**Comment by HedvigS** [comment]
Check!
For Pamona we in the GB team need a dutch speaker. We'll sort that out somehow, no worries :)

**Comment by SimonGreenhill** [comment]
(reopening until this change is actually made)

**Comment by kirbykat** [comment]
Done as part of #183
