### ISSUE TITLE
Release procedure 2.0

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#186]
- [x] release dplace-data
- [x] release pydplace
- [x] release clld/dplace2
- [x] switch DNS entry
- [x] edit dplace2 config in appconfig:
  - [x] change domain to d-place.org
  - [x] remove HTTP basic auth
- [x] deploy dplace2 to production
- [x] update DNS entry for d-place.shh.mpg.de (Monday)

**Comment by chrzyki** [comment]
[https://d-place.shh.mpg.de](https://d-place.shh.mpg.de) now redirects to [https://d-place.org](https://d-place.org) with a `301`.

```
$ curl d-place.shh.mpg.de
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://d-place.org">here</a>.</p>
<hr>
<address>Apache/2.2.22 (Debian) Server at d-place.shh.mpg.de Port 80</address>
</body></html>
```
