### ISSUE TITLE
Download tables (CSV files) of more than one variable

### ISSUE THREAD

**Issue by kirbykat** [D-PLACE/dplace-data#190]
A user writes: "How can I download a table of combined variables from D-PLACE? I can download a file when only viewing a single variable."  

Can we make this possible again? In D-PLACE 1.0, a user could use D-PLACE to "build" a dataset of 3 variables (or more). Rows were societies, columns included the selected variables, any comments linked to the variable+society, and all contextual information (e.g., year, society name, alternative names, language (glottolog ID), language family, any admin notes on corrections to the code relative to historic versions of the dataset).

**Comment by xrotwang** [comment]
How would we handle multiple values for the same society and variable? AFAIR the old app just picked the "first" - in whatever order the data was pulled out of the db - which is not what we want, right?
