### ISSUE TITLE
Glottocode for Cf5 not updated

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#194]
In the comment for society Cf5, French Canadians (https://github.com/D-PLACE/dplace-data/blob/master/datasets/EA/societies.csv#L883) it says

> `stan1290 replaced with queb1247 in Oct 2017 because it is a better match

But that appears not to have happened - the assigned Glottocode is still stan1290.

**Comment by SimonGreenhill** [comment]
Looks good to me. @kirbykat ?
