### ISSUE TITLE
bowern_and_atkinson2012: Pama-Nyungan

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#198]

**Comment by kirbykat** [comment]
Authors contacted with request for posterior probability distribution 17 April 2019.

**Comment by kirbykat** [comment]
In touch with Claire Bowern about this - first set of files shared were log files rather than posterior trees.

**Comment by SimonGreenhill** [comment]
Files lost in hard drive crash :(
