### ISSUE TITLE
michael_et_al2015: Tupi-Guarani

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#201]
Need to contact authors

No supplemental material available at https://escholarship.org/uc/item/1331v899

**Comment by kirbykat** [comment]
Authors contacted with request for posterior probability distribution 17 April 2019.

**Comment by SimonGreenhill** [comment]
Added in https://github.com/D-PLACE/dplace-data/commit/4076bf083b00facc70c268a30ad75b97d6493fb7
