### ISSUE TITLE
de Filippo et al. 2012: Niger-Congo

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#204]
Not available in supplementary materials. Need to contact authors

https://www.ncbi.nlm.nih.gov/pubmed/21109585

**Comment by kirbykat** [comment]
Email request sent, I'll follow up next week if I haven't heard back.

**Comment by kirbykat** [comment]
Received from Cesare de Filippo. @SimonGreenhill if there are any problems with the files please let me know, otherwise I think we can close this issue.

**Comment by SimonGreenhill** [comment]
Needs taxon mapping, have asked @chrzyki to pass on this to a hiwi

**Comment by chrzyki** [comment]
Work on this has begun. Thanks for preparing the data/work package, @SimonGreenhill.

**Comment by SimonGreenhill** [comment]
oh this is done.
