### ISSUE TITLE
check scale used for branch lengths in phylogenies

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#221]
We should either scale the branch lengths for all phylogenies to millenia, or keep the scaling factor as metadata.

**Comment by SimonGreenhill** [comment]
This is tracked in the 'scaling' column of [index.csv](https://github.com/D-PLACE/dplace-data/blob/master/phylogenies/index.csv). No conversions have been made.

**Comment by SimonGreenhill** [comment]
Ok, I've checked the ones I know and updated the details in https://github.com/D-PLACE/dplace-data/commit/755c54d407453d0aa568da79abc5a83caa51d2dd

I need to investigate grollemund, honkola, and sicoli & holton more.

**Comment by xrotwang** [comment]
Thanks! So for everything with a `scaling` of `millenia` or `years` **and** a posterior distribution, we should be good to compute additional constraints, right?

**Comment by SimonGreenhill** [comment]
Yes, and I've just found a centuries. Can phyltr adjust branches? we should perhaps add a conversion to a common timescale.

**Comment by SimonGreenhill** [comment]
I've identified the others except Grollemund. I think this is in 10000s of years?

**Comment by xrotwang** [comment]
@SimonGreenhill I think for the ones with absolute times, converting to a common timescale is easy enough - and since there's the explicit column in the metadata it should be transparent enough, that timescales can differ. And there could possibly be phylogenies with relative branch lenghts, right? So for these a common timescale wouldn't be available anyway.

**Comment by xrotwang** [comment]
closing in favor of the more specific #226
