### ISSUE TITLE
posterior.trees in Grollemund et al. 2015 seems broken

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#225]
The format of [`posterior.trees`](https://github.com/D-PLACE/dplace-data/blob/master/phylogenies/grollemund_et_al2015/posterior.trees) in Grollemund et al. 2015 looks suspicious:
- Trees are listed right in the `translate` block.
- There's no `end` marker for the `Trees` block.

**Comment by xrotwang** [comment]
See https://github.com/lmaurits/phyltr/issues/16#issuecomment-453955556 for context.

**Comment by SimonGreenhill** [comment]
Actually, easier to fix this by hand, PR in #235
