### ISSUE TITLE
Standardise the time scales for phylogenies

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#226]
It seems, `posterior.trees` for Grollemund et al. 2015 mixes branch length and change rate in a composite data type à la `1234.3@0.56`. If read this way, the scale factor for the branch lengths seems to be `years`, giving ~6,800 years root age for Atlantic-Congo.

**Comment by SimonGreenhill** [comment]
Ok, we need to remove @... from these trees. What's the best way to do it? I can write some code/regex to do this, or should we use phyltr as discussed in https://github.com/lmaurits/phyltr/issues/16#issuecomment-453955556 ?

**Comment by xrotwang** [comment]
`phyltr` would be the right tool for the job, though. And it uses `ete3` for the low-level nexus reading and writing, like `pydplace` - so it only adds the functionality we want without any overhead.

**Comment by SimonGreenhill** [comment]
I just realised that the summary trees and the posterior trees have different scales for this dataset. This is annoying.

Should we standardise the scales?

**Comment by SimonGreenhill** [comment]
```sh
phyltr cat < my.trees | phyltr scale -s 100 > out.trees
```

**Comment by xrotwang** [comment]
This kind of standardization is now done in Phlorest.
