### ISSUE TITLE
Potential issue with geographic location of Ungazikmit

### ISSUE THREAD

**Issue by Joseph-Watts** [D-PLACE/dplace-data#229]
Cassie Sprules (@csprules), who is working with me on a database, identified a potential issue with the geographic location of the Binford and EA society "Ungazikmit". Most of the source materials seem to focus on a group that is located on St. Lawrence Island and the Chukchi Peninsula, and the glottolog on D-Place also places them in St. Lawrence Island. However, the geographic location listed on D-Place (and the Binford R package) is inland Siberia. The distance between these locations is about 700km.

We were wondering whether there might be an error in Binford's dataset that has been inherited in D-Place and the EA. The difference in location could be accounted for by someone (potentially Binford) using the geographic coordinates 64.00, 173.00 (inland Siberia), as opposed to 64.00, -173.00 (the edge of the Chukchi Peninsula). It seems like it would be an easy mistake to make and could be worth checking?

**Comment by SimonGreenhill** [comment]
Well spotted, thanks. @kirbykat -- can one of your hiwi's track this down?

**Comment by kirbykat** [comment]
This may already be in Xinyu’s database, but either way I suspect @csprules’ hunch is correct. We have found a number of such errors in the datasets. Xinyu is currently working on collecting lat/longs of sites at which orginal ethnographic work was carried out (I.e., ethnographic work upon which coded data are based).

**Comment by kirbykat** [comment]
Sorry - I meant to add I will check with Xinyu and get back to you ASAP.

**Comment by Joseph-Watts** [comment]
Ok cool, I'd be keen to hear about any updates on the lat/long coordinates for Binford's dataset as we are currently working on extending a subset of it. How will you be archiving the PDFs? We have PDFs for a fair few Binford cultures that I'm not sure where to store once coding is complete. I guess these kinds of things cant be made public due to copyright, but it could be cool if we had a private storage place that we could share materials.

**Comment by kirbykat** [comment]
Agreed! It would be great to have a shared archive. I’ve talked a bit with @xrotwang about this, and I think we should be able to store them on an MPI server for internal use. Let me try to get a list together of all the PDFs we have so far (currently in various google drives, which we’re happy to share). The “big” part of this is going to be scanning texts that are not available in PDF format...I’m not sure how far we’ll get with that, but did get some advice from Piers and his hiwi on using the “book eye” scanner in the library. So, more on that in the next month, I think.

**Comment by kirbykat** [comment]
I agree with the change, which has now been applied to both the EA and Binford coordinates for Ungazikmit.
