### ISSUE TITLE
Updates to D-PLACE society and language data

### ISSUE THREAD

**Issue by kirbykat** [D-PLACE/dplace-data#242]
Society names:
If17 and SCCS108 (xd832) - preferred name "Marshallese - Jaluit atoll"
Ee4 (xd656) - preferred name change to "Central Tibetans" to differentiate it from eHRAF society "West Tibetans"
B292, Nb22 and WNAI2 (xd1082) - preferred name change to "South Tlingit", to differentiate from "North Tlingit"

xd_id to language updates:
xd832 = rali1241
xd104 = meru1245
xd546 = nucl1266 (to differentiate it from eHRAF Serb-speaking society "Montenegrins")
xd656 = dbus1238 (to differentiate it from mnga1238-speaking eHRAF society "West Tibetans")
xd366 = luwo1239, change based on Tucker 1931
xd649 = chao1239 (dialect-level match, based on review of primary sources while trying to figure out eHRAF matches)

**Comment by kirbykat** [comment]
Changes made to societies.csv files, once approved I think this issue can be closed.

**Comment by xrotwang** [comment]
see #244, #245, #243
