### ISSUE TITLE
Rufiji?

### ISSUE THREAD

**Issue by lmaurits** [D-PLACE/dplace-data#263]
The Grollemund et al phylogeny maps a taxa to `rufji1234`.  That code is retired, and there's nothing else named "Rufiji" in Glottolog.  Does anyone know what the story is here?

**Comment by lmaurits** [comment]
Ah, okay, Rufijic (`rufji1236`) is a subfamily now, so I guess that's what became of Rufiji.  I guess at the very least this mapping should be changed to that code, but I'll see if I can figure out if any of the descendant languages are a likely match...

**Comment by xrotwang** [comment]
If in doubt, ask @d97hah . He should know about the anguages in the Grollemund paper (having helped mapping them before).

**Comment by lmaurits** [comment]
I've found their main language list published with their paper.  It just calls the language "Rufiji", but does give coordinates of -8, 38.7, which suggests one of the Matumbic varieties...

**Comment by kirbykat** [comment]
@lmaurits here is a file that (may?) help - has Grollemund ISO - glotto - D-PLACE links, and Rebecca Grollemund answered  a few questions in it. Looks like she had that tip matched to iso code rui, but that probably doesn't get you any farther: https://www.dropbox.com/s/955769so1h6lagj/BantuGrollemund_AdminNotes_Update_April2018_2.xlsx?dl=0

**Comment by lmaurits** [comment]
Thanks for that!  Ethnologue lists a few alternative names for the `rui` ISO code, but none of them seem to be in use by Glottolog for Rufijic languages.

**Comment by kirbykat** [comment]
looks like glottolog sets rui = ndg; but grollemund has an ndg already...(from: https://glottolog.org/resource/languoid/id/nden1248):

E16/E17/E18/E19 has Ndengereko [ndg] as well as Rufiji [rui] entry, but these terms denote the same language -- Ndengereko being the name of the language and Rufiji the name of a river and the area around it ( Ström, Eva-Marie 2009 ). (Rufiji may also be used as a name for a subfamily that includes Ndengereko and other languages ( Chuo Kikuu cha Dar es Salaam 2009 :xi).) KiRufiji is a natural Swahili way to denote the language spoken in the Rufiji area, and this term is used in the Tanzania census, which is a plausible origin of the E16/E17/E18/E19 entry. I wish to thank Eva-Marie Ström for discussion on the Ndengereko [ndg] and Rufiji [rui] entries. See also: Rufiji [rui].

**Comment by lmaurits** [comment]
Thanks @d97hah!  That's one of the two Matumbic languages whose Glottolog coordinates are a close match with the "Rufiji" coordinates in the supplementary material from Grollemund et al., which further corroborates that matching.  Is everyone happy for me to map this leaf to `nden1248` in the PR that I'm preparing?

**Comment by lmaurits** [comment]
Ah, whoops, as @kirbykat points out there is already something mapped to that glottocode, and named Ndengereko, so that can't possibly be what their Rufiji is supposed to be...

**Comment by xrotwang** [comment]
@lmaurits hard to say. If all lexical items for the two languages are identical as well, it may just be the same language.

**Comment by lmaurits** [comment]
Okay, looking at all Rufijic languages in Glottolog, Grollemund has other taxa with names clearly matching Matengo, Mpoto, Ngindo, Matumbi, Ndengereko and Mbunga.  So the *only* Rufijic language in Glottolog which we don't already have an obvious match for is Nindi (`nind1242`).

**Comment by xrotwang** [comment]
In [lexibank](https://github.com/lexibank/grollemundbantu/blob/master/cldf/languages.csv) both languages are mapped to `nden1248`, but the lexical data differs. I don't think there's a simple answer here.
