### ISSUE TITLE
Finding EA reference

### ISSUE THREAD

**Issue by HedvigS** [D-PLACE/dplace-data#264]
On [the page for EA as a dataset](https://d-place.org/contributions/EA) this reference appears:

Murdock, G. P., R. Textor, H. Barry, III, D. R. White, J. P. Gray, and W. T. Divale. 1999. Ethnographic Atlas. World Cultures 10:24-136 (codebook)

But I can't find this anywhere with this particular list of authors. Help :)?

[I can find Gray's "A corrected EA" codebook from 1998](https://www.researchgate.net/publication/228580573_A_corrected_ethnographic_atlas) and the old versions from the 60's and 80's. I'm struggling to find this particular ref with this list of authors though. [The current repos for the journal doesn't have 10](https://escholarship.org/uc/wc_worldcultures/16/1) and [the old host page doesn't have this 1999 codebook either as far as I can tell](http://eclectic.ss.uci.edu/~drwhite/worldcul/atlas.htm). It says 

> Gray's codebook, published in World Cultures volume 10, number 1, which is reprinted below, makes them much more accessible.

But, there ain't no "below" :) and the publication they link to elsewhere on that page is [the 1998 codebook](http://eclectic.ss.uci.edu/~drwhite/worldcul/Codebook4EthnoAtlas.pdf). At the end of that PDF, there is a 1999-dated reference describing the contents of a CD data disk, but Textor and other authors found in the ref above aren't typed out.

I'm guessing that World Cultures 10 had parts that were published in 1998 and other parts that were published in 1999.

I've probably misunderstood and am looking in the wrong place etc, however help would be appreciated so that I cite and access this resource correctly with all the right authors. 

Thanks!

**Comment by kirbykat** [comment]
Hi @HedvigS, I'm sorry I missed the notification for this issue. Here is the codebook we referenced on the EA Dataset page, direct from the World Cultures CD. You should be able to open it with a text editor: https://www.dropbox.com/s/65ib28e24ys5k7a/ATL.COD?dl=0

Note, however, that we transferred all the info from this codebook to our own, and made some further corrections as detailed in the [supplementary materials](https://doi.org/10.1371/journal.pone.0158391.s002) of the Kirby et al. 2016 D-PLACE paper (also noted in the 'AdminComments' field, or equivalent, in the csv files below). 

The corrected codebook can be reconstructed by joining the following two csv files by the fields "var_id" (in "codes.csv") and "id" (in "variables.csv")

Codes: https://github.com/D-PLACE/dplace-data/blob/master/datasets/EA/codes.csv

Variables: https://github.com/D-PLACE/dplace-data/blob/master/datasets/EA/variables.csv

Thanks for letting us know that this was unclear. We are working on providing "flat files" for each D-PLACE release, which will basically be pre-joined versions of all relevant csv files in the repo for each cultural dataset (EA, Binford, etc.). We will have a data file and codebook for each.

Kate

**Comment by xrotwang** [comment]
@HedvigS does this resolve the issue - i.e. can we close it?
