### ISSUE TITLE
Wrong taxon column in robinson_and_holton_2012 taxa.csv

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#267]
`taxon` in [taxa.csv](https://github.com/D-PLACE/dplace-data/blob/master/phylogenies/robinson_and_holton2012/taxa.csv) doesn't match `taxlables` in [summary.trees](https://github.com/D-PLACE/dplace-data/blob/master/phylogenies/robinson_and_holton2012/summary.trees).

**Comment by SimonGreenhill** [comment]
Ahh, I guess I went off the IDs in the lexibank dataset... fixed in https://github.com/D-PLACE/dplace-data/pull/270
