### ISSUE TITLE
Upgrade to Glottolog 4.2.1

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#275]
Trying to upgrade to Glottolog 4.2.1, there are two issues with dialects that have disappeared:

1. [EA society Awuna](https://d-place.org/society/Ag37) is mapped to [awun1244](https://glottolog.org/files/glottolog-4.0/awun1244.html) - a dialect of [Ewe](https://glottolog.org/resource/languoid/id/ewee1241), which isn't included in v4.2.1 anymore.

2. [Kitchen's semitic phylogeny](https://d-place.org/phylogenys/kitchen_et_al2009) maps Geto to [gyet1240](https://glottolog.org/files/glottolog-4.0/gyet1240.html) - a dialect of [Sebat Bet Gurage](https://glottolog.org/resource/languoid/id/seba1251), which isn't in v4.2.1.

**Comment by xrotwang** [comment]
@d97hah any ideas?

**Comment by d97hah** [comment]
You mean there are associations that are no longer current? Should be a
relatively small list?

Pada tanggal Kam, 16 Jul 2020 pukul 08.56 Robert Forkel <
notifications@github.com> menulis:

**Comment by SimonGreenhill** [comment]
Yep -- Geto which was gyet1240, and Awuna which was awun1244. 

The Geto data are originally from here: https://glottolog.org/resource/reference/id/91520

**Comment by SimonGreenhill** [comment]
I think Awuna should be Anlo (https://glottolog.org/resource/languoid/id/angl1262) based on [this](https://en.wikipedia.org/wiki/Anlo_Ewe)

**Comment by d97hah** [comment]
Geto is Gyeta [gyet1241] in 4.2.1



Pada tanggal Kam, 16 Jul 2020 pukul 15.19 Simon J Greenhill <
notifications@github.com> menulis:

**Comment by d97hah** [comment]
Yes Anlo [angl1262]

Pada tanggal Kam, 16 Jul 2020 pukul 15.24 Simon J Greenhill <
notifications@github.com> menulis:

**Comment by SimonGreenhill** [comment]
great, thanks Harald!
