### ISSUE TITLE
Not updated: geographic coordinates for societies in 'tdwg societies' file 

### ISSUE THREAD

**Issue by kirbykat** [D-PLACE/dplace-data#280]
It looks like lat/long coordinates for societies Koreans (Ed1) and Negri Sembilan (Ej16) in this file have not been updated/corrected, while those in the datasets > EA > societies.csv file HAVE. I'm believe (but am not sure - @xrotwang?) that the tdwg societies file is only used for display/mapping on the site. Can we pull the tdwg lat/lon from individual society.csv files?

Updated (columns "Lat" and "Long":
https://github.com/D-PLACE/dplace-data/blob/master/datasets/EA/societies.csv

Not updated:
https://github.com/D-PLACE/dplace-data/blob/master/geo/societies_tdwg.json

**Comment by xrotwang** [comment]
`societies_tdwg.json` is only used to populate the [`region` attribute](https://github.com/clld/dplace2/blob/11a96e510d264cf372b2370001ca90c50c25cea5/dplace2/scripts/initializedb.py#L122) - so the issue shouldn't have any effect on the app (or most analyses).
The file will be regenerated when [`dplace tdwg`](https://github.com/D-PLACE/pydplace/blob/master/src/pydplace/commands/tdwg.py) is run, i.e. when a new [release is created](https://github.com/D-PLACE/dplace-data/blob/master/RELEASING.md#assign-societies-to-tdwg-regions).

**Comment by xrotwang** [comment]
I'll leave the issue open until I run `dplace tdwg` (to confirm that I was correct above :) ).

**Comment by kirbykat** [comment]
@xrotwang that sounds good, but in that case should it have updated when 2.1 was released? The changes to the coordinates of Koreans (Ed1) and Negri Sembilan (Ej16)  were made before the release of 2.1, I'm almost certain. Thanks!

**Comment by kirbykat** [comment]
(My concern is for people who try to build a flat file for analysis, and decide to pull lat lon from the tdwg file instead of from the societies file. Obvs. not a big deal, but will start introducing errors/make things less reproducible.)

**Comment by SimonGreenhill** [comment]
yeah, we need to make a new release of DPLACE very soon

**Comment by xrotwang** [comment]
@kirbykat yes, you are right, there's potential for confusion. I think I didn't re-run the region identification, because there were no new societies (between 2.0 and 2.1). @SimonGreenhill and I were thinking about some sort of CLDFy release format for D-PLACE data. This might help in making more transparent what we think should be used and how.

**Comment by SimonGreenhill** [comment]
See also #321

**Comment by xrotwang** [comment]
Resolved with the new model of curating the data.
