### ISSUE TITLE
tanggu or tangga

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#281]
Should society `Ig21`, which is currently mapped to "Tangu [tang1355]" be mapped to "Tangga [tang1348]".

See https://github.com/glottolog/glottolog/issues/554

**Comment by SimonGreenhill** [comment]
Looks like it should be tang1348 , the ethnographies mention Boeng island, [which means it's Tangga](https://en.wikipedia.org/wiki/Tanga_Islands) not Tangu (spoken in the Lakes Plains region of New Guinea). 

Agree @xrotwang and @kirbykat ?

**Comment by xrotwang** [comment]
Agree - the "island vs. inland New Guinea" distinction seems convincing.

**Comment by kirbykat** [comment]
That sounds reasonable to me too. It looks like this is the first change to this glottocode, which probably means no one caught it until now.

**Comment by SimonGreenhill** [comment]
ok, done!
