### ISSUE TITLE
Correction to EA009, for which 'shortName' of codes 5 and 6 is reversed

### ISSUE THREAD

**Issue by kirbykat** [D-PLACE/dplace-data#285]
The correct 'codeDescription' and 'shortName' for EA009 codes 5 and 6 [caps not needed, but highlight corrections]

5 | Polygynous, with polygyny general and not reported to be preferentially sororal, and co-wives typically occupying separate quarters | Polygyny, non-sororal SEPARATE
-- | -- | --
6 | Polygynous, with polygyny general and not reported to be preferentially sororal, and co-wives not reported to occupy separate quarters | Polygyny, non-sororal COHABIT

**Comment by SimonGreenhill** [comment]
Done in #286
