### ISSUE TITLE
Is Beraber really a correct society name?

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#29]
Should [Beraber](https://d-place.shh.mpg.de/society/Cd7) be "Berber"?

**Comment by SimonGreenhill** [comment]
It's Beraber in the original data (see e.g. [here](https://pdfs.semanticscholar.org/c421/c3e3a2a7c959b727c9c123be24dfd11508a5.pdf) )

**Comment by xrotwang** [comment]
ok
