### ISSUE TITLE
Release new dplace-data v2.2

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#290]
Hi @xrotwang, when you get a minute, can you please release 2.2. I don't think we need anything of the open issues handled for the time being.

**Comment by xrotwang** [comment]
Do you need this before the weekend?

**Comment by xrotwang** [comment]
And do we need this imported in the web app right away?

**Comment by SimonGreenhill** [comment]
No & No.

**Comment by xrotwang** [comment]
What Glottolog version should release with? 4.2 or 4.3?

**Comment by xrotwang** [comment]
See https://github.com/D-PLACE/dplace-data/pull/291

**Comment by SimonGreenhill** [comment]
may as well go for the latest and greatest!

**Comment by xrotwang** [comment]
In particular since the other changes barely merit a new minor version (see https://github.com/D-PLACE/dplace-cldf/commit/bca2e2de714aecc91d25c9b97aeb48ae15433c1d) :)

**Comment by xrotwang** [comment]
See https://github.com/D-PLACE/dplace-data/releases/tag/v2.2.0

**Comment by SimonGreenhill** [comment]
thanks @xrotwang !

**Comment by kirbykat** [comment]
Yes, thanks @xrotwang!
