### ISSUE TITLE
Update Glottolog mappings in phylogeny "grollemund_et_al_2015"

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#292]
Via @d97hah

> I've had reason to look over the Grollemund 2015 language id:s again and I noticed some errors, mostly because I realized many of the lists were in Grollemund 2012 were the sources are given, which is far more information than just the name. My best understanding is reflected in the lgcode-part of the latest hh.bib.

This likely affects https://github.com/D-PLACE/dplace-data/blob/master/phylogenies/grollemund_et_al2015/taxa.csv

**Comment by SimonGreenhill** [comment]
this should be fixed now.
