### ISSUE TITLE
Update description of EA031

### ISSUE THREAD

**Issue by HedvigS** [D-PLACE/dplace-data#312]
For EA031 I believe that the description needs to be updated and/or synchronised. The[ D-PLACE clld web app for example describes level 6 as "1000+ no towns"](https://d-place.org/parameters/EA031) but the[ EA codebook from 1998 calls it "1,000 without any town of more than 5,000".](https://web.econ.ku.dk/bentzen/Codebook4EthnoAtlas.pdf) The codes.csv table here in this repos calls it "[More than 1,000 persons in the absence of indigenous urban aggregations"](https://github.com/D-PLACE/dplace-data/blob/master/datasets/EA/codes.csv#L278).

More is better here I think, so take the most informative description and put it everywhere. I lean towards the EA codebook one.

**Comment by xrotwang** [comment]
`codes.csv` has a long and a short description (name) for each code. The short one here is the one used in the web app:

var_id | code | description | name
-- | -- | -- | --
EA031 | 6 | More than 1,000 persons in the absence of indigenous urban aggregations | 1000+ no towns

**Comment by HedvigS** [comment]
Thanks @xrotwang , that clarifies the difference between the web app and codes tables.
 
The issue that neither of those mean the same thing as the EA codebook still stands.

**Comment by kirbykat** [comment]
Hi @HedvigS. When we digitized the EA data for D-PLACE, we went back to Murdock's original published code definitions. Whoever created the 1998 codebook used their own words to simplify Murdock's definitions, but sometimes important details were lost in the process. The "short name" for each code is indeed less descriptive - originally it was included to make legends easier to read. In any case, you should use the "description" on D-PLACE as the "true" meaning of the code (for the EA, the SCCS still needs to be corrected based on the original articles). You can also always go back to the article in which Murdock first published a particular variable (they are all available online), and check D-PLACE wording against the wording he used.

**Comment by kirbykat** [comment]
@HedvigS this doc provides a bit more detail (see 'Cultural Variables' and 'Codes' sections): https://journals.plos.org/plosone/article/file?type=supplementary&id=10.1371/journal.pone.0158391.s002

If you think this could be made clearer on the site (maybe under FAQ?) please let us know, and feel free to suggest wording or draft something!

**Comment by HedvigS** [comment]
Thanks @kirbykat ! That helps a lot.

So, level 6 for EA031 means that there are no "towns" whatsoever? I'm a bit confused by that,  because level 7 then jumps up to at least one town of 5,000 or more. It seems like the state of having one or more towns of less than 5,000 each sort of falls between the levels. Or perhaps I'm misunderstanding something?

**Comment by kirbykat** [comment]
Thanks for spotting this @HedvigS. Part of the description for level 6 was missing - probably chopped off in OCR process. I have updated it in the repo, will be merged to site on next update. 

Code description should read: "More than 1,000 persons in the absence of indigenous urban aggregations of more than 5,000"
Short name corrected to "1000-5000"

Here is the original description from Murdock 1962 (Ethnology Vol 1(2):265-283). Note that it is adapted from Murdock's previous attempt at a big cross-cultural dataset, the World Ethnographic Sample (WES). I have found that in some cases the descriptions in the original WES articles are even more informative. 

![image](https://user-images.githubusercontent.com/7913855/152702234-ca1ea2d9-cda1-45e4-8f40-108787cd8e3a.png)

**Comment by HedvigS** [comment]
Thanks @kirbykat ! No worries, happy to help.

This variable is a bit tricky to interpret, which is why I was digging into the specifics a bit. Levels 1-5 are sort of of a different kind than 6-8. It's a bit tricky to know what "local community" is as it seems to shift between those levels, that's why I was struggling. Elsewhere I've seen "local community" identified as "group of people who regularly interact face-to-face", and that can't possibly apply to cities of more than 50,000.

**Comment by SimonGreenhill** [comment]
ok, so this is fixed now?

**Comment by HedvigS** [comment]
@SimonGreenhill Yep. Thanks for closing the issue.
