### ISSUE TITLE
Lau on ABVD phylogeny misallocated to Lau Fijian 

### ISSUE THREAD

**Issue by fionajordan** [D-PLACE/dplace-data#322]
Lau (Ih4/xd870) ethnographic data refers to Lau Fijians, and all is correct apart from the allocation to Lau on the ABVD language set, where it is linked to a Southeast Solomonic language (ISO LLU, lauu1247) 
The Glottolog code (laua1243) is correct. 

Thanks to Brea MacCauley for bringing this to my attention!

**Comment by xrotwang** [comment]
Superseded by https://github.com/phlorest/gray_et_al2009/issues/2
