### ISSUE TITLE
Barabra (SCCS39) - incorrect coordinates

### ISSUE THREAD

**Issue by hrncirv** [D-PLACE/dplace-data#324]
Barabra (SCCS39) has incorrect coordinates (23°N, 39°07'E) that place them in the Arabian Peninsula instead of Egypt.
https://d-place.org/society/SCCS39

According to Murdock & White (1996) they are located 22° to 24°N, 32° to 33°E.

![SCCS39_Nubians](https://user-images.githubusercontent.com/69760928/222766825-356618a9-a229-479c-8e6a-d1450d8f95dd.png)

See also EA entry Barabra (Cd1) with coordinates 23°N, 33°E
https://d-place.org/society/Cd1

**Comment by xrotwang** [comment]
Note: This also applies to the related EA society:
```
$ grep xd507 ../*/cldf/societies.csv
../dplace-dataset-ea/cldf/societies.csv:Cd1,Barabra,23,33,kenu1236,Barabra (Cd1),xd507,Kenuzi Nubians,1920,,,23,33,Original,,Northern Africa
../dplace-dataset-sccs/cldf/societies.csv:SCCS39,Barabra,23,39.11,kenu1236,Kenuzi Nubians  (SCCS39),xd507,Kenuzi Nubians,1900,,,23,38.75,Revised,,Arabian Peninsula
```

**Comment by xrotwang** [comment]
Superseded by https://github.com/D-PLACE/dplace-dataset-ea/issues/6 and https://github.com/D-PLACE/dplace-dataset-sccs/issues/4
