### ISSUE TITLE
add environmental data for all languages in glottolog?

### ISSUE THREAD

**Issue by HedvigS** [D-PLACE/dplace-data#326]
I've been struggling with MODIS lately, I want to get NPP data on more points in the Pacific than there are data for that variable in D-PLACE.

Any chance that any future release of D-PLACE would include more data-points for variables form EcoClimate and MODIS, where there essentially already is data for the entire world? I'm guessing a choice was made to only extract this info for socities that also had data in EA, SCCS etc. But... any chance of extending the sample for these variables?

For example, all varieties that are languages in glottolog could get a data-point for it's glottolog lat/long point and a certain radius around it. It'd mean adding a lot more societies to D-PLACE, but maybe it's worth it :)?

(Yes, I'm struggling with MODIS and I'm hoping that who-ever made the original extracting for D-PLACE could work their "magic" again. I might still succeed, but the amount of complexity of MODIS was rather surprising.)

**Comment by xrotwang** [comment]
I think that's rather unlikely.

1. As you say, D-PLACE has data linked to societies. The only way a society gets into D-PLACE is via an ethnographic dataset containing observations about it. Declaring Glottolog some sort of pseudo-Society-set would go against this principle.

2. MODIS data is time-series data and D-PLACE societies carry metadata such as a "focal year". So extracting MODIS data per society requires judging whether focal year and available data match.

I agree, though, that - ideally - the procedure to derive the MODIS-related variables in D-PLACE from "raw" data should be reproducible by running a piece of published code. But realistically, that's a big ask.

**Comment by HedvigS** [comment]
that's okay, I get it. I'll struggle on with MODIS on my own.
