### ISSUE TITLE
Chekiang

### ISSUE THREAD

**Issue by olcsheehan** [D-PLACE/dplace-data#332]
This society is accompanied by the note ‘Kaihsienkung Village, Chekiang’ (today this would be romanized ‘Kaixiangong Village, Zhejiang’). However, according Fei (1939), which appears to be the main source, this village is not in Chekiang but in the neighbouring province of Kiangsu (Jiangsu). For this reason, I would suggest renaming this society 'Jiangsu' or 'Kiangsu'.

**Comment by xrotwang** [comment]
There's a couple more [sources](https://github.com/D-PLACE/dplace-data/blob/master/sources.bib) used for this society in the EA and SCCS data:
- chien1967
- fei1946
- fried1953
- lang1946
- linebargeretal1956
- smith1970
- fried1953

Do you have an idea whether they agree on the location?

**Comment by olcsheehan** [comment]
Hi Robert, 

I’ve looked into the other sources. Lang (1946), Linebarger et al. (1956), and Smith (1970) are available on archive.org. They’re all about China as a whole rather than any specific locality. I haven’t been able to find Ch’ien (1967), but based on the title (‘The Government and Politics of China’) I assume this is similar. Fried (1953) focuses on Ch’uhsien (Chuxian) in the province of Anhwei (Anhui). So it would seem that none of the sources are about Chekiang. 

The note ‘Kaihsienkung Village, Chekiang’ strongly suggests that Murdock had this village in mind when coding this society, but for some reason got its location wrong. 

Best wishes,

Oliver

**Comment by xrotwang** [comment]
@olcsheehan so the geo-coordinates are correct, but the name (the province) is wrong?

**Comment by olcsheehan** [comment]
The coordinates are slightly off. I believe this is the place: [](https://www.google.com/maps/place/Kaixiangong+Car+Station/@31.0098716,120.4444634,11.21z/data=!4m6!3m5!1s0x35b36a9d3707c0c7:0xe2f2e5c1c74da280!8m2!3d30.976948!4d120.493942!16s%2Fg%2F1vlz8czn?entry=ttu)

**Comment by olcsheehan** [comment]
The coordinates are only slightly off. Kaixiangong village is not marked on Google Maps, but there's a place called 'Kaixiangong Car Station' that matches the maps and descriptions in Fei (1946). The coordinates are 30.98, 120.49 (I tried posting a link but it didn't seem to work).

**Comment by hrncirv** [comment]
Hi, I checked this and @olcsheehan is right. The coordinates are approximately **31 N, 120.5 E**, and the province is "**Kiangsu**" according to Fei (1946), now written as **Jiangsu** https://en.wikipedia.org/wiki/Jiangsu

However, the question is whether to name the culture by province name or just generically "Chinese" as was the original SCCS name. https://d-place.org/society/SCCS114

Alternatively it can be named "Wu Chinese" (according to the dialect) or "Han Chinese" (according to the ethnicity) https://en.wikipedia.org/wiki/Wu_Chinese-speaking_people

See also HRAF - correct coordinates and name "Han Chinese"

![chinese](https://github.com/D-PLACE/dplace-data/assets/69760928/39499971-2fb2-4325-8ae0-cdfe788ae7e1)

**Comment by xrotwang** [comment]
Going with "Han Chinese", following HRAF, would seem the best option to me.

**Comment by hrncirv** [comment]
I'm fine with that.

**Comment by olcsheehan** [comment]
‘Han Chinese’ would be fine if Chekiang were the only society in the EA meeting this definition, but there’s also Cantonese (Ed16), Min Chinese (Ed6), and Shantung (Ed10).

**Comment by xrotwang** [comment]
So, if Chekiang is the only society for Wu Chinese in SCCS, we could rename to "Chinese" there (the particuliarities will still be conveyed through the "sub_case" field of each datapoint), and rename to Kiangsu or Jiangsu for EA, since, a more fine-grained name seems to be intended by the D-PLACE editors with "Chekiang".

**Comment by olcsheehan** [comment]
That would make sense :)

**Comment by SimonGreenhill** [comment]
@xrotwang -- perhaps we need to display things as {{ name }} - {{subcase}} on the website to make this clearer? Is it the case that a given {{name}} can have multiple subcases? or is it a 1:1 mapping?

**Comment by olcsheehan** [comment]
> @xrotwang -- perhaps we need to display things as {{ name }} - {{subcase}} on the website to make this clearer? Is it the case that a given {{name}} can have multiple subcases? or is it a 1:1 mapping?

I think there might be a few cases of that - e.g. Esa (Ca10) is a subgroup of Somali (Ca2) - but not many.

**Comment by xrotwang** [comment]
@SimonGreenhill @olcsheehan there are quite a few cases of the same society having values for different sub-cases. Most of them seem to be in Binford:
```sql
sqlite> select cldf_languagereference, count(distinct Sub_Case) as c from valuetable group by cldf_languagereference order by c desc limit 20;
B72|11
B374|9
B355|8
B298|8
B118|8
B357|6
B65|5
B383|5
B372|5
B359|5
B204|5
B381|4
B299|4
B22|4
B1|4
B9|3
B85|3
B75|3
B6|3
B389|3
```
E.g. here's the subcases for B72:
```sql
sqlite> select distinct Sub_Case from valuetable where cldf_languagereference = 'B72';

Special reference to Was Nyae !Kung
Special reference to Dobe !Kung
Special reference to Nyae Nyae !Kung
General
Rainy Season, Mobile !Kung, Camps 1, 3, 5, 6, 9
Dry Season, Mobile !Kung, Camps 2, 4, 7, 10-16
Dry Season, Dobe !Kung
Nyae Nyae !Kung
Dobe !Kung
Southern Auen !Kung
Auen !Kung
```

Displaying sub-case somewhat prominently can only be done on the value pages (or would you want to list all sub-cases on the society page as well?), and that's where we already do that: e.g. https://d-place.org/valuesets/B021-B72

**Comment by xrotwang** [comment]
Superseded by https://github.com/D-PLACE/dplace-dataset-ea/issues/3 and https://github.com/D-PLACE/dplace-dataset-sccs/issues/3
