### ISSUE TITLE
Incorrect location for Mari (Ch4, xd568)

### ISSUE THREAD

**Issue by olcsheehan** [D-PLACE/dplace-data#334]
Mari (Ch4, xd568) have been placed in the Caucasus region at 43.00 N, 46.00 E. This is a long way south and slightly west of the real location of the Mari (about 56.5 N, 48.00 E, based on the location of the Republic of Mari El). The location currently provided for Mari is the same as for Chechen (Ci7, xd583), and since the original name of Mari in the EA was Cheremis, I wonder if some data accidentally got copied from one row to another.

**Comment by xrotwang** [comment]
@olcsheehan I've moved the issue here https://github.com/D-PLACE/dplace-dataset-ea/issues/1

I'm in the process of reorganizing the D-PLACE data, splitting the individual dataset into separate repositories. The societies in question here are in the EA dataset.
