### ISSUE TITLE
Add new environmental data from ecoclimate.org

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#34]
Carlos Botero has extracted data from ecoclimate for d-place societies. Advantage is that ecoclimate data are closer match to time foci of d-place cultural data. Carlos has data, and we (Mike Gavin and Patrick Kavanagh) do too, when team is ready to add it to d-place.

**Comment by SimonGreenhill** [comment]
[New.DPLACE.EnvVars.26Jul2016.txt](https://github.com/D-PLACE/dplace-data/files/915411/New.DPLACE.EnvVars.26Jul2016.txt)

**Comment by SimonGreenhill** [comment]
[Citation information](http://ecoclimate.org/citation/)

**Comment by SimonGreenhill** [comment]
@xrotwang  -- was the above file added? (New.DPLACE.EnvVars...)

**Comment by xrotwang** [comment]
Yes, we got the numbers. `AnnualMeanPrecipitation` turned out to be `MonthlyMeanPrecipitation`, though.

**Comment by xrotwang** [comment]
See https://github.com/D-PLACE/dplace-data/issues/151#issuecomment-334709899
