### ISSUE TITLE
Update README.md file about society mapping

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#46]
https://github.com/D-PLACE/dplace-data/blob/master/scripts/README.md#precomputed-society-region-mapping

**Comment by xrotwang** [comment]
What do you think about cobbling together a `dplacedata` cli to make the automatic data curation scripts accessible in a unified way?

**Comment by xrotwang** [comment]
The code to access the data programmatically from `dplace_app.load` should probably moved here (and imported when loading).
