### ISSUE TITLE
Add more checks to dplace check

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#61]
It strikes me that the specification in [./datasets/README.md](https://github.com/D-PLACE/dplace-data/tree/master/datasets/README.md) could make the start of a set of testcases for the datasets e.g. 

* each dataset must have variables.csv which contains a set of columns.
* each dataset must have data.csv with a set of specific columns
* each dataset must be listed in index.csv
* each dataset may have other files which must contain specific columns
* some columns have a distinct format (e.g. Lat/Long should be floats, glottocode should a valid glottocode)

**Comment by xrotwang** [comment]
We have the `dplace check` command, which loops through all datasets, and instantiates `Society` and `Variable` objects. We could make it loop through data as well. `Lat` and `Long` are already validated in this process, see https://github.com/D-PLACE/dplace-data/blob/master/pydplace/api.py#L108-L109

**Comment by SimonGreenhill** [comment]
Ok, makes sense to have it there too then.

**Comment by SimonGreenhill** [comment]
Fixed in #66
