### ISSUE TITLE
Add tests for phylogenies directory

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#63]
The phylogenies directory could also be tested:

* each directory must contain summary.trees
* each directory must contain taxa.csv
* each directory must be listed in index.csv
* taxa.csv must contain all tips names in summary.trees (or just the linkable ones?)
* taxa.csv column glottocode must be a valid glottocode or null
* taxa.csv column xd_ids must contain valid xd_ids or null
* taxa.csv column soc_ids must contain valid soc_ids or null

**Comment by xrotwang** [comment]
Most of these are already covered by the `dplace check` command.

**Comment by SimonGreenhill** [comment]
Ok, added the ones we don't have to #65
