### ISSUE TITLE
Fix incorrect xd_ids

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#68]
Are these related to missing Jorgensen/SCCS data? 

* ERROR   sicoli_and_holton2014: invalid xd_id xd1425
* ERROR   dunn_et_al2011_utoaztecan: invalid xd_id xd1439
* ERROR   dunn_et_al2011_utoaztecan: invalid xd_id xd1440
* ERROR   sicoli_and_holton2014: invalid xd_id xd1434
* ERROR   sicoli_and_holton2014: invalid xd_id xd1431
* ERROR   sicoli_and_holton2014: invalid xd_id xd1423
* ERROR   sicoli_and_holton2014: invalid xd_id xd1438

**Comment by xrotwang** [comment]
I guess so:
```
dplace-data$ grep xd1425 legacy/ALL_soc_ids_to_xd_ids_24Feb2016.csv 
Jorgensen,J43,xd1425,Cahto,Kato Athapaskan (J43),"Kato, Kato Athapaskan",
```

**Comment by xrotwang** [comment]
So when we add these datasets, we must make sure to pull out the `xd_id`s from `legacy/ALL_soc_ids_to_xd_ids_24Feb2016.csv`.

**Comment by SimonGreenhill** [comment]
These no longer show in `dplace check` and look like they're all in `datasets/WNAI/societies.csv`
