### ISSUE TITLE
Identify and tag version 1

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#71]
We need to identify which commit to use as our version one marker and tag it so Zenodo can archive a V1

**Comment by SimonGreenhill** [comment]
This looks like a good candidate. Pre-dates the major revisions that happened:

https://github.com/D-PLACE/dplace-data/tree/960979b0e705265b34534436d90ead18e3aaccfc

**Comment by SimonGreenhill** [comment]
@xrotwang -- do you know how to do this and get Zenodo to snapshot it?

**Comment by xrotwang** [comment]
good question. should be possible to make a release based on an older commit, though. will find out.

**Comment by xrotwang** [comment]
What about the one you already tagged? https://github.com/D-PLACE/dplace-data/releases/tag/v1.0

**Comment by xrotwang** [comment]
Feeding https://github.com/D-PLACE/dplace-data/releases/tag/v1.0 into ZENODO by hand may be the cleanest way to get a DOI for the first release.

**Comment by SimonGreenhill** [comment]
[Woah](https://media.giphy.com/media/OK27wINdQS5YQ/giphy.gif).

**Comment by xrotwang** [comment]
Should I do the upload? May make sense, because the automatic upload for newer versions would also happen under my user account ...

**Comment by SimonGreenhill** [comment]
yes please!

**Comment by xrotwang** [comment]
Maybe we should also extract the citations from `(datasets|phylogenies)/index.csv` into a `SOURCES.md` to make them more prominent?

**Comment by SimonGreenhill** [comment]
Great idea.

**Comment by xrotwang** [comment]
And this page: https://d-place.shh.mpg.de/howtocite should probably have a dynamic part created from the db as well.

**Comment by xrotwang** [comment]
@SimonGreenhill please check this
https://zenodo.org/record/439199#.WNzGOkf-vCI
There are ways to add grant info in ZENODO, too. If you think this should be done, let me know.

**Comment by SimonGreenhill** [comment]
Looks good. I'll add an issue to the front-end for the howtocite page.

**Comment by SimonGreenhill** [comment]
Actually, adding the grant info might be politically good. How hard is this? it should all be listed in the Kirby et al paper

**Comment by xrotwang** [comment]
not too hard. a bit of copy&paste I guess. will do.

**Comment by xrotwang** [comment]
@SimonGreenhill I looked into the paper but couldn't find any actual grant numbers. Are there any?

**Comment by xrotwang** [comment]
Just realized ZENODO only has special support for grants in two funding schemes:

> European Commission FP7 and Horizon 2020 grants only. For general funding acknowledgements, please use the Additional Notes field.

**Comment by SimonGreenhill** [comment]
Ahh, ok, can we just paste the statement from the paper?

**Comment by xrotwang** [comment]
Basically

> European Commission FP7 and Horizon 2020 grants only. For general funding acknowledgements, please use the Additional Notes field.

right?

**Comment by xrotwang** [comment]
oops, I mean

> D-PLACE was developed with generous support from the National Evolutionary Synthesis Center (www.nescent.org) and the Max Planck Institute for the Science of Human History (www.shh.mpg.de/en)

**Comment by SimonGreenhill** [comment]
Looks good.

**Comment by xrotwang** [comment]
Done: https://zenodo.org/record/439199#.WN0eWEf-thE
