### ISSUE TITLE
Add source URL to `index.csv` for phylogenies and datasets

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#73]
The [description of sources on D-PLACE](https://d-place.shh.mpg.de/source) contains URLs in particular for environmental datasets, these should be put into `index.csv`, loaded into the database and dynamically inserted into the HTML page.

**Comment by SimonGreenhill** [comment]
Added to datasets/index.csv

**Comment by SimonGreenhill** [comment]
Fixed.
