### ISSUE TITLE
Command to list societies covered for given variables

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#74]
To easily assess D-PLACE coverage for particular topics, it would be nice to be able to list societies (including glottocode, top-level language family, region and macroarea) given a set of variables (or datasets) and maybe ways to filter `NA` or missing data values.

**Comment by HedvigS** [comment]
Yes this would be useful :)

**Comment by SimonGreenhill** [comment]
Isn't this what [extract](https://github.com/D-PLACE/pydplace/blob/master/src/pydplace/commands.py#L156) does?
