### ISSUE TITLE
R's default phylogenetics library APE misreads glottolog global tree

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#81]
This will generate a lot of support emails so we should fix it.

```r
> library('ape')
> tree <- read.nexus('summary.trees')
> plot(tree)

Error in plot.phylo(tree) : there are single (non-splitting) nodes in your tree; you may need to use collapse.singles()

# and collapse.singles doesn't work either:
> tree <- collapse.singles(tree)

Error in tree$node.label[oldnodes - n] : only 0's may be mixed with negative subscripts
```

Unsure where this error is coming from, I will have to investigate when I get time.

**Comment by SimonGreenhill** [comment]
A spot check of 3 families works, so it sounds like the combining. Hmm I wonder if my PR that makes ETE merge families might have helped (haven't regenerated the tree since then). Have to head home now, but will try check this tonight unless you get to it.

**Comment by xrotwang** [comment]
I have to do pizza-eating and similar in Bologna - so won't get in your way :)

**Comment by SimonGreenhill** [comment]
I've made a bunch of refactorings in #83

This fixes some of the issues, but I think others must be upstream in glottolog.

e.g. this tree for kiow1265 errors:
```
    tree glottolog_kiow1265 = (kiow1266,((sani1273,sant1421),hano1247),jeme1245,(sout2961,((taos1236))));
```

...while removing the singleton nodes (i.e. the extra brackets around taos1236) such that: 

```
    tree glottolog_kiow1265 = (kiow1266,((sani1273,sant1421),hano1247),jeme1245,(sout2961,taos1236));
```

fixes the problem. 

Key changes in PR #83 are (feel free to disagree):

* Don't generate a taxa list block in the nexus, as it's not needed and this makes the tree files smaller.
* No longer store glottolog branch lengths, as these are meaningless, and we don't use them in DPLACE anyway, and they were generating some oddities (e.g. the preserve_branch_length in ete3 sums the branches so that if a node had 4 removed it would have a branch length of 4, while others would just have 1).
* Do not store node labels as I don't think we use them -- but it just occurred to me that we might use them somewhere (i.e. if a society is mapped to a node rather than a tip?)
* sort output in glottolog.csv (slower, but more idempotent file)

The R script in ./scripts/check_trees.r can identify trees with singleton nodes: 

* ../phylogenies/glottolog_afro1255/summary.trees
* ../phylogenies/glottolog_atla1278/summary.trees
* ../phylogenies/glottolog_kiow1265/summary.trees
* ../phylogenies/glottolog_mand1469/summary.trees
* ../phylogenies/glottolog_global/summary.trees

(and I think the global error is due to the child trees)

**Comment by SimonGreenhill** [comment]
e.g. glottolog_afro1255 can be fixed with (`git diff --word-diff-regex=.` format, look for \[-(-\]'s)

```diff

#NEXUS
Begin trees;
    tree glottolog_afro1255 = ((((cent2194,susi1238),kaby1243),((ghat1242,hogg1238),(tadh1242,timb1263),(ioul1238,tawa1287)),(tach1249,(tidi1241,tumz1238),tari1263),siwi1239,guan1277,zena1248),(((((bura1292,marg1265),park1239),(musg1254,budu1265),psik1239,lagw1237,sout3051),((hwan1240,tera1251),(baca1246,bata1314,gude1246),mafa1239)),((([-(-]kano1249,araw1280)[-)-],(((kare1348,nucl1695),dera1248),ngas1240)),(ngiz1242,bogh1241)),masa1322),((abab1239,amar1281,bish1251,hade1248),((burj1242,(gede1246,sida1246)),(((((arbo1245,daas1238),nort3051),((west2721,bora1271),kons1243)),tsam1247),afar1241)),(qima1242,bili1260),(goro1270,iraq1241)),egyp1246,(((jewi1240,hebr1245),(((nort3137,sout3119),sana1295),((nort3140,nort3141,sunn1238),sout3123),((algi1247,cons1245,oran1236),hass1238,liby1240,(sahi1245,sout3114,tuni1260),(jebl1238,sout3117)),meso1252,(egyp1253,said1239,((bath1248,char1283),(khar1296,nort3133,west2773))))),((seba1251,amha1245),(tigr1271,mans1267))));
end;
```

**Comment by SimonGreenhill** [comment]
I've fixed the trees in #91, but we should probably figure out where these singletons come from.

**Comment by xrotwang** [comment]
Yeah, fixing the trees manually isn't going to work in the long run.

**Comment by SimonGreenhill** [comment]
Ok, got it: singletons are caused by the glottolog trees have excess named nodes. This is a problem if there is only one daughter of a named node e.g. here is the glottolog tree for kiow1266

```
(kiow1266,((hano1247)ariz1237,(namb1296,pojo1241,sani1273,sanj1276,sant1421,tesu1245)tewa1260)tewa1261,(piro1248,((isle1245,sand1277)sout2961,(picu1248,(taos1236)nort1550)taos1246)tiwa1255)tiwa1254,jeme1245)kiow1265
```

...which fails this check in R:

```{r}
tree <- '(kiow1266,((hano1247)ariz1237,(namb1296,pojo1241,sani1273,sanj1276,sant1421,tesu1245)tewa1260)tewa1261,(piro1248,((isle1245,sand1277)sout2961,(picu1248,(taos1236)nort1550)taos1246)tiwa1255)tiwa1254,jeme1245)kiow1265'

tree <-  paste0(tree, ';')  # ensure a ; at the end
summary(read.tree(text=tree))

Error in if (sum(obj[[i]]$edge[, 1] == ROOT) == 1 && dim(obj[[i]]$edge)[1] >  : 
  missing value where TRUE/FALSE needed
```

Changing the tree to remove the singleton nodes of "(hano1247)ariz1237" -> "hano1247" and  "(taos1236)nort1550" -> "taos1236":

```
(kiow1266,(hano1247,(namb1296,pojo1241,sani1273,sanj1276,sant1421,tesu1245)tewa1260)tewa1261,(piro1248,((isle1245,sand1277)sout2961,(picu1248,taos1236)taos1246)tiwa1255)tiwa1254,jeme1245)kiow1265
```

...works. So, an upstream decision for glottolog: collapse nodes with single descendants to just branches to keep R happy, or document this?

**Comment by xrotwang** [comment]
Hm. I see. Above dialect level Glottolog actually has this policy of not allowing sub-groups with just one (family or language) descendant. For dialects, though, there's a conflict: We also have the policy that each dialect must be attached to a language (or another dialect). Thus, for cases where there is (currently) only one dialect registered in Glottolog for a language, we run into the problem described above.

The best way to deal with this would probably be
- extend [`Languoid.newick`](https://github.com/clld/glottolog/blob/master/pyglottolog/languoids.py#L101-L112) with an option to drop single dialects,
- use this option when [creating the trees for D-PLACE](https://github.com/D-PLACE/dplace-data/blob/master/pydplace/glottolog.py#L76).

**Comment by SimonGreenhill** [comment]
closing as this is an upstream problem and no-one seems to have run into this issue. Reopen if needed.
