### ISSUE TITLE
Once PR #80 is merged, `sources.bib` should be completed

### ISSUE THREAD

**Issue by xrotwang** [D-PLACE/dplace-data#86]
Tasks to clean/complete `datasets/sources.bib`:
- Find records with `citation_ea` **and** `citation_binford`, figure out if they are the same, if so, identifiy, i.e. complete the record and remove the `citation_*` fields. If not, leave as is.
- Find records without `glottolog_*` field and complete them.

**Comment by SimonGreenhill** [comment]
This is completed now, right?

**Comment by xrotwang** [comment]
About to integrate the wnai refs.
Am 19.04.2017 16:37 schrieb "Simon J Greenhill" <notifications@github.com>:
