### ISSUE TITLE
Update text on "how to cite" that is included at top of every downloaded csv file

### ISSUE THREAD

**Issue by kirbykat** [D-PLACE/dplace-data#87]
Research that uses data from D-PLACE should cite both the original source(s) of  the data and the paper by Kirby et al. in which D-PLACE was first presented  (e.g., research using cultural data from the Binford Hunter-Gatherer dataset: "Binford (2001);  Binford and Johnson (2006); Kirby et al. 2016)." The reference list should include the date data were  accessed and URL for D-PLACE (https://d-place.org), in addition to the full references for Binford (2001),  Binford and Johnson (2006), and Kirby et al. 2016.

[changed from "Kirby et al. Submitted" to "Kirby et al. 2016." Open to other adjustments.

**Comment by SimonGreenhill** [comment]
Think this is an issue with the [website](https://github.com/D-PLACE/dplace/issues/474)
