### ISSUE TITLE
Update language matches - corrections received from Harald

### ISSUE THREAD

**Issue by kirbykat** [D-PLACE/dplace-data#88]
ISO 639-3 and glottolog ids for about 10 societies updated here. I can also talk with Simon/Hans today about how to add directly to repository.

[April2017_language_updates.zip](https://github.com/D-PLACE/dplace-data/files/913600/April2017_language_updates.zip)

**Comment by xrotwang** [comment]
Yes, please talk to them. Updating data wholesale isn't recommended anymore. Instead, small changes to the now authoritative data files in the repos (possibly through the API) are the way to go.

**Comment by SimonGreenhill** [comment]
Taken care of now.
