### ISSUE TITLE
Current CSV download of cultural data misses many ISO codes

### ISSUE THREAD

**Issue by kirbykat** [D-PLACE/dplace-data#89]
Many missing ISO codes when download cultural data for all cultures. Could this be because there is a 'look up' between glottolog id and iso code, which doesn't work when the glottolog id refers to a 'dialect'-level language?

**Comment by SimonGreenhill** [comment]
Think this is a website problem, so moved [here](https://github.com/D-PLACE/dplace/issues/476)
