### ISSUE TITLE
Release dplace-data on PyPI 

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#93]

**Comment by SimonGreenhill** [comment]
```
running register
running egg_info
writing requirements to pydplace.egg-info/requires.txt
writing pydplace.egg-info/PKG-INFO
writing top-level names to pydplace.egg-info/top_level.txt
writing dependency_links to pydplace.egg-info/dependency_links.txt
writing entry points to pydplace.egg-info/entry_points.txt
reading manifest file 'pydplace.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.tsv' under directory 'pydplace'
writing manifest file 'pydplace.egg-info/SOURCES.txt'
running check
warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied
```

**Comment by SimonGreenhill** [comment]
Things we need:

* either (author and author_email) or (maintainer and maintainer_email) in setup.py (@xrotwang happy to use yours?)

* LICENSE. CC-BY? GPLv3?

**Comment by xrotwang** [comment]
@SimonGreenhill yes, go ahead with forkel@shh.mpg.de

When it comes to licenses, I tend to use Apache 2, mainly because that's more or less default for any javascript libraries, and I don't want to run into trouble just because a project uses any of these.

**Comment by SimonGreenhill** [comment]
Hmm. Apache grants patent rights. We may need to be concerned about that. We probably need a dual license? one for the code and one for the data?

**Comment by xrotwang** [comment]
ah, true. Well, in that case I'd just go with CC-BY. The code doesn't have too many dependencies, and doesn't add too much to the data ...

**Comment by SimonGreenhill** [comment]
See #107

**Comment by SimonGreenhill** [comment]
And we're [on PyPI](https://pypi.python.org/pypi/pydplace)

**Comment by xrotwang** [comment]
But you didn't upload any releases yet, did you? In any case, `pip install pydplace` doesn't seem to work yet.

Also, could you give me admin rights for the package on PyPI, too? I'm `xrotwang`.

**Comment by SimonGreenhill** [comment]
Should be up now, and you should have admin rights too?

**Comment by xrotwang** [comment]
Yes, got it.
